In [123]:
import pandas as pd

import os
path2data = './raw_data/NL to LTL Synthetic Dataset'
data = os.listdir(path2data)
data = [x for x in data if (  ("train" in x and 'unrestricted' in x and "~" not in x) )]
data

['unrestricted_train_dataset-50.csv', 'unrestricted_train_dataset-140.csv']

In [124]:
import spot
def simplify_formula(formula_str):

    f = spot.formula(formula_str)
    return f


def extract_atomic_propositions(formula_str):
    f = spot.formula(formula_str)
    aps = spot.atomic_prop_collect(f)
    
    mapping = []
    for i, atom in enumerate(aps):
        mapping.append(str(atom))
        

    return mapping

In [125]:
lista = []
for elem in data:
    df = pd.read_csv(path2data + '/' + elem)[['ltl','en']]
    df['source'] = str(elem)
    lista.append( df )
result = pd.concat(lista, ignore_index=True)
result

,ltl,en,source
0,G(!( brake_is_pressed | house_is_open | train_...,under no circumstances either the brake is pre...,unrestricted_train_dataset-50.csv
1,G(!( car_starts | semaphore_is_red | bar_is_up )),"under no condition either a car starts, a sema...",unrestricted_train_dataset-50.csv
2,G(!( escalator_speeds_up & train_derails & hou...,"under no condition the escalator speeds up, th...",unrestricted_train_dataset-50.csv
3,G(!( constructor_instantiate_objects & bar_is_...,it is never the case that a constructor instan...,unrestricted_train_dataset-50.csv
4,G(!( table_has_been_moved & table_is_brown & m...,it never happens that the table has been moved...,unrestricted_train_dataset-50.csv
...,...,...,...
189995,G(( elevator_rises ) -> G(( sensor_captures_da...,each time the elevator rises then always when ...,unrestricted_train_dataset-140.csv
189996,G(( train_derails ) -> G(( escalator_moves ) -...,when the train derails then it will happen tha...,unrestricted_train_dataset-140.csv
189997,G(( brake_is_pressed ) -> G(( constructor_inst...,the brake is pressed involves that whenever th...,unrestricted_train_dataset-140.csv
189998,G(( elevator_is_blocked ) -> G(( sensor_captur...,when the elevator is blocked then if the senso...,unrestricted_train_dataset-140.csv
189999,G(( house_collapses ) -> G(( semaphore_is_gree...,a house collapses involves that every time the...,unrestricted_train_dataset-140.csv

In [126]:
result = result.rename(columns={'ltl': 'original LTL', 'en': 'original NL'})

result

,original LTL,original NL,source
0,G(!( brake_is_pressed | house_is_open | train_...,under no circumstances either the brake is pre...,unrestricted_train_dataset-50.csv
1,G(!( car_starts | semaphore_is_red | bar_is_up )),"under no condition either a car starts, a sema...",unrestricted_train_dataset-50.csv
2,G(!( escalator_speeds_up & train_derails & hou...,"under no condition the escalator speeds up, th...",unrestricted_train_dataset-50.csv
3,G(!( constructor_instantiate_objects & bar_is_...,it is never the case that a constructor instan...,unrestricted_train_dataset-50.csv
4,G(!( table_has_been_moved & table_is_brown & m...,it never happens that the table has been moved...,unrestricted_train_dataset-50.csv
...,...,...,...
189995,G(( elevator_rises ) -> G(( sensor_captures_da...,each time the elevator rises then always when ...,unrestricted_train_dataset-140.csv
189996,G(( train_derails ) -> G(( escalator_moves ) -...,when the train derails then it will happen tha...,unrestricted_train_dataset-140.csv
189997,G(( brake_is_pressed ) -> G(( constructor_inst...,the brake is pressed involves that whenever th...,unrestricted_train_dataset-140.csv
189998,G(( elevator_is_blocked ) -> G(( sensor_captur...,when the elevator is blocked then if the senso...,unrestricted_train_dataset-140.csv
189999,G(( house_collapses ) -> G(( semaphore_is_gree...,a house collapses involves that every time the...,unrestricted_train_dataset-140.csv

In [127]:

result['Spot LTL'] = result['original LTL'].apply(lambda x: str(simplify_formula(x)))
result['APs'] = result['original LTL'].apply(lambda x: extract_atomic_propositions(x))
result

,original LTL,original NL,source,Spot LTL,APs
0,G(!( brake_is_pressed | house_is_open | train_...,under no circumstances either the brake is pre...,unrestricted_train_dataset-50.csv,G!(brake_is_pressed | house_is_open | train_is...,"[brake_is_pressed, house_is_open, train_is_cro..."
1,G(!( car_starts | semaphore_is_red | bar_is_up )),"under no condition either a car starts, a sema...",unrestricted_train_dataset-50.csv,G!(bar_is_up | car_starts | semaphore_is_red),"[car_starts, semaphore_is_red, bar_is_up]"
2,G(!( escalator_speeds_up & train_derails & hou...,"under no condition the escalator speeds up, th...",unrestricted_train_dataset-50.csv,G!(escalator_speeds_up & house_is_built & trai...,"[escalator_speeds_up, train_derails, house_is_..."
3,G(!( constructor_instantiate_objects & bar_is_...,it is never the case that a constructor instan...,unrestricted_train_dataset-50.csv,G!(bar_is_closing & constructor_instantiate_ob...,"[constructor_instantiate_objects, bar_is_closi..."
4,G(!( table_has_been_moved & table_is_brown & m...,it never happens that the table has been moved...,unrestricted_train_dataset-50.csv,G!(manager_collect_claims & table_has_been_mov...,"[table_has_been_moved, table_is_brown, manager..."
...,...,...,...,...,...
189995,G(( elevator_rises ) -> G(( sensor_captures_da...,each time the elevator rises then always when ...,unrestricted_train_dataset-140.csv,G(elevator_rises -> G(sensor_captures_data -> ...,"[train_is_crossing, sensor_captures_data, elev..."
189996,G(( train_derails ) -> G(( escalator_moves ) -...,when the train derails then it will happen tha...,unrestricted_train_dataset-140.csv,G(train_derails -> G(escalator_moves -> Feleva...,"[train_derails, escalator_moves, elevator_is_b..."
189997,G(( brake_is_pressed ) -> G(( constructor_inst...,the brake is pressed involves that whenever th...,unrestricted_train_dataset-140.csv,G(brake_is_pressed -> G(constructor_instantiat...,"[brake_is_pressed, constructor_instantiate_obj..."
189998,G(( elevator_is_blocked ) -> G(( sensor_captur...,when the elevator is blocked then if the senso...,unrestricted_train_dataset-140.csv,G(elevator_is_blocked -> G(sensor_captures_dat...,"[sensor_captures_data, elevator_is_blocked, tr..."
189999,G(( house_collapses ) -> G(( semaphore_is_gree...,a house collapses involves that every time the...,unrestricted_train_dataset-140.csv,G(house_collapses -> G(semaphore_is_green -> F...,"[table_is_brown, house_collapses, semaphore_is..."

In [128]:
import re
def swap_row_propositions(row, prop_col, text_col):
    propositions = row[prop_col]
    text = row[text_col]
    
    if not isinstance(propositions, list) or not isinstance(text, str):
        return text

    # 1. Create mapping for THIS row: {'car starts': 'car_starts'}
    mapping = {p.replace('_', ' '): p for p in propositions}
    
    # 2. Build a regex pattern from these specific keys
    # Sort by length descending to match longest phrases first
    sorted_keys = sorted(mapping.keys(), key=len, reverse=True)
    pattern = re.compile(r'\b(' + '|'.join(map(re.escape, sorted_keys)) + r')\b')
    
    # 3. Replace matches in the text using the mapping
    return pattern.sub(lambda m: mapping[m.group(0)], text)

# Apply the function across the rows
result['ap_NL'] = result.apply(
    lambda row: swap_row_propositions(row, 'APs', 'original NL'), 
    axis=1
)

In [129]:
result

,original LTL,original NL,source,Spot LTL,APs,ap_NL
0,G(!( brake_is_pressed | house_is_open | train_...,under no circumstances either the brake is pre...,unrestricted_train_dataset-50.csv,G!(brake_is_pressed | house_is_open | train_is...,"[brake_is_pressed, house_is_open, train_is_cro...",under no circumstances either the brake_is_pre...
1,G(!( car_starts | semaphore_is_red | bar_is_up )),"under no condition either a car starts, a sema...",unrestricted_train_dataset-50.csv,G!(bar_is_up | car_starts | semaphore_is_red),"[car_starts, semaphore_is_red, bar_is_up]","under no condition either a car_starts, a sema..."
2,G(!( escalator_speeds_up & train_derails & hou...,"under no condition the escalator speeds up, th...",unrestricted_train_dataset-50.csv,G!(escalator_speeds_up & house_is_built & trai...,"[escalator_speeds_up, train_derails, house_is_...","under no condition the escalator_speeds_up, th..."
3,G(!( constructor_instantiate_objects & bar_is_...,it is never the case that a constructor instan...,unrestricted_train_dataset-50.csv,G!(bar_is_closing & constructor_instantiate_ob...,"[constructor_instantiate_objects, bar_is_closi...",it is never the case that a constructor_instan...
4,G(!( table_has_been_moved & table_is_brown & m...,it never happens that the table has been moved...,unrestricted_train_dataset-50.csv,G!(manager_collect_claims & table_has_been_mov...,"[table_has_been_moved, table_is_brown, manager...",it never happens that the table_has_been_moved...
...,...,...,...,...,...,...
189995,G(( elevator_rises ) -> G(( sensor_captures_da...,each time the elevator rises then always when ...,unrestricted_train_dataset-140.csv,G(elevator_rises -> G(sensor_captures_data -> ...,"[train_is_crossing, sensor_captures_data, elev...",each time the elevator_rises then always when ...
189996,G(( train_derails ) -> G(( escalator_moves ) -...,when the train derails then it will happen tha...,unrestricted_train_dataset-140.csv,G(train_derails -> G(escalator_moves -> Feleva...,"[train_derails, escalator_moves, elevator_is_b...",when the train_derails then it will happen tha...
189997,G(( brake_is_pressed ) -> G(( constructor_inst...,the brake is pressed involves that whenever th...,unrestricted_train_dataset-140.csv,G(brake_is_pressed -> G(constructor_instantiat...,"[brake_is_pressed, constructor_instantiate_obj...",the brake_is_pressed involves that whenever th...
189998,G(( elevator_is_blocked ) -> G(( sensor_captur...,when the elevator is blocked then if the senso...,unrestricted_train_dataset-140.csv,G(elevator_is_blocked -> G(sensor_captures_dat...,"[sensor_captures_data, elevator_is_blocked, tr...",when the elevator_is_blocked then if the senso...
189999,G(( house_collapses ) -> G(( semaphore_is_gree...,a house collapses involves that every time the...,unrestricted_train_dataset-140.csv,G(house_collapses -> G(semaphore_is_green -> F...,"[table_is_brown, house_collapses, semaphore_is...",a house_collapses involves that every time the...

In [130]:
result.to_csv('./processed_data/NL to LTL Synthetic Dataset/processed_data.csv', index=False, sep=';')

In [172]:
def english_to_ltl(s):
    s = s.replace('globally', 'G')
    s = s.replace('finally', 'F')
    s = s.replace('next', 'X')
    s = s.replace('or', '|')
    s = s.replace('double_implies', '<->')
    s = s.replace('implies', '->')
    s = s.replace('and', '&')
    s = s.replace('not', '!')
    s = s.replace('negation', '!')
    s = s.replace('imply', '->')
    s = s.replace('until', 'U')
    return s

eng_to_ltl_dict = {'globally': 'G',
'finally': 'F',
'next': 'X',
'or': '|',
'double_implies': '<->',
'implies': '->',
'and': '&',
'not': '!',
'negation': '!',
'imply': '->',
'until': 'U'}

In [166]:
path2data = './raw_data/VLTL-Bench/new/'
data = os.listdir(path2data)
data = [x for x in data ]
data

['search_and_rescue.jsonl', 'traffic_light.jsonl', 'warehouse.jsonl']

In [175]:
df = {}
for file in data:
    df[file] = pd.read_json(os.path.join(path2data, file), lines=True)

reserved = ['globally', 'finally', 'next', 'or', 'double_implies', 
            'implies', 'and', 'until', 'not', 'negation', 'imply', '(', ')']

def wrap_propositions(token_list):
    return [f'"{item}"' if item not in reserved else item for item in token_list]

def swap_oprerations(token_list):
    return [f'{eng_to_ltl_dict[item]}' if item in eng_to_ltl_dict else item for item in token_list]

for file in df:
    df[file]['source'] = file
    df[file]['original NL'] = df[file]['sentence'].str.join(' ')
    df[file]['tl'] = df[file]['tl'].apply(wrap_propositions)
    df[file]['tl'] = df[file]['tl'].apply(swap_oprerations)
    df[file]['original LTL'] = df[file]['tl'].str.join(' ').replace('""', '"', regex=True)
    df[file]['Spot LTL'] = df[file]['original LTL'].apply(english_to_ltl)

def get_flat_map(nested_dict):
    # We combine all args_canon -> args_ref pairs into one dict
    if not isinstance(nested_dict, dict):
        return {}
    
    flat_map = {}
    for prop in nested_dict.values():
        # Zip canon keys to ref values and update our master map
        flat_map.update(zip(prop.get('args_ref', []), prop.get('args_canon', [])))
    return flat_map

for file in df:
    df[file]['AP_dict'] = df[file]['prop_dict'].apply(lambda x: {x[y]['action_ref']: x[y]['action_canon'] for y in x})
    
    df[file]['AP_misc_dict'] = df[file]['prop_dict'].apply(get_flat_map)
    df[file]['merged_dict'] = df[file].apply(lambda row: row['AP_misc_dict'] | row['AP_dict'], axis=1)

def replace_from_mapping(row, text_column):
    text = str(row[text_column])
    mapping = row['merged_dict']
    
    # Iterate through the dictionary for this specific row
    for old_val, new_val in mapping.items():
        # replace() handles all instances of that key in the string
        text = text.replace(old_val, new_val)
    
    return text

import csv

for file in df:
    # Apply the function to your text column
    # Replace 'my_text_col' with the actual name of your string column
    df[file]['original NL'] = df[file].apply(replace_from_mapping, axis=1, text_column='original NL')
    df[file]['Spot LTL'] = df[file]['Spot LTL'].apply(lambda x: str(simplify_formula(x)))
    df[file]['APs'] = df[file]['Spot LTL'].apply(lambda x: extract_atomic_propositions(x))
    df[file][['source','APs','original NL','original LTL','Spot LTL']].to_csv('./processed_data/VLTL-Bench/new/'+file.split('.')[0]+'.csv', index=False, sep=';',index_label=False, quoting=csv.QUOTE_MINIMAL)
#

In [176]:
path2data = './raw_data/VLTL-Bench/prev/'
data = os.listdir(path2data)
data = [x for x in data ]
data

['GLTL.jsonl', 'navi.jsonl', 'conformal.jsonl', 'cleanup_world.jsonl']

In [177]:
df = {}
for file in data:
    df[file] = pd.read_json(os.path.join(path2data, file), lines=True)

reserved = ['globally', 'finally', 'next', 'or', 'double_implies', 
            'implies', 'and', 'until', 'not', 'negation', 'imply', '(', ')']

def wrap_propositions(token_list):
    return [f'"{item}"' if item not in reserved else item for item in token_list]


for file in df:
    df[file]['source'] = file
    df[file]['original NL'] = df[file]['sentence'].str.join(' ')
    df[file]['tl'] = df[file]['tl'].apply(wrap_propositions)
    df[file]['original LTL'] = df[file]['tl'].str.join(' ').replace('""', '"', regex=True)
    df[file]['Spot LTL'] = df[file]['original LTL'].apply(english_to_ltl)

def get_flat_map(nested_dict):
    # We combine all args_canon -> args_ref pairs into one dict
    if not isinstance(nested_dict, dict):
        return {}
    
    flat_map = {}
    for prop in nested_dict.values():
        # Zip canon keys to ref values and update our master map
        flat_map.update(zip(prop.get('args_ref', []), prop.get('args_canon', [])))
    return flat_map

for file in df:
    df[file]['AP_dict'] = df[file]['prop_dict'].apply(lambda x: {x[y]['action_ref']: x[y]['action_canon'] for y in x})
    
    df[file]['AP_misc_dict'] = df[file]['prop_dict'].apply(get_flat_map)
    df[file]['merged_dict'] = df[file].apply(lambda row: row['AP_misc_dict'] | row['AP_dict'], axis=1)

def replace_from_mapping(row, text_column):
    text = str(row[text_column])
    mapping = row['merged_dict']
    
    # Iterate through the dictionary for this specific row
    for old_val, new_val in mapping.items():
        # replace() handles all instances of that key in the string
        text = text.replace(old_val, new_val)
    
    return text

import csv

for file in df:
    # Apply the function to your text column
    # Replace 'my_text_col' with the actual name of your string column
    df[file]['original NL'] = df[file].apply(replace_from_mapping, axis=1, text_column='original NL')
    df[file]['Spot LTL'] = df[file]['Spot LTL'].apply(lambda x: str(simplify_formula(x)))
    df[file]['APs'] = df[file]['Spot LTL'].apply(lambda x: extract_atomic_propositions(x))
    df[file][['source','APs','original NL','original LTL','Spot LTL']].to_csv('./processed_data/VLTL-Bench/prev/'+file.split('.')[0]+'.csv', index=False, sep=';',index_label=False, quoting=csv.QUOTE_MINIMAL)
#

In [187]:
import json
from pprint import pprint

with open('./raw_data/ConformalNL2LTL/calibration.json') as json_data:
    d = json.load(json_data)
    json_data.close()

for ind in range(len(d)):
    d[ind]['ltlequ'] = d[ind]['ltlequ'].strip("/")
    if "U" in d[ind]['ltlequ']:
       d[ind]['ltlequ'] = d[ind]['ltlequ'].replace("U", " U ")
    
    d[ind]['Spot LTL'] = str(simplify_formula(str(d[ind]['ltlequ'])))

d

[{'nlTask': 'Take a picture of building 2',
  'ltlequ': '<>(building_2&&photo)',
  'Spot LTL': 'F(building_2 & photo)'},
 {'nlTask': 'Take bottle 3 from store 1 and put it in hospital 2',
  'ltlequ': '<>(shop_1&&<>(p_bottle_3&&<>(hospital_2&&pd)))',
  'Spot LTL': 'F(shop_1 & F(p_bottle_3 & F(hospital_2 & pd)))'},
 {'nlTask': 'Go to parking lot 2 and pick up dish 2',
  'ltlequ': '<>(parking_lot_2&&p_dish_2)',
  'Spot LTL': 'F(p_dish_2 & parking_lot_2)'},
 {'nlTask': 'Go to hospital 3 and pick up water bottle 4 while never entering pharmacy 2',
  'ltlequ': '<>(hospital_3&&p_bottle_4)&&[]!pharmacy_2',
  'Spot LTL': 'F(hospital_3 & p_bottle_4) & G!pharmacy_2'},
 {'nlTask': 'Stay in parking lot 4 until you reach car 5',
  'ltlequ': 'parking_lot_4 U car_5',
  'Spot LTL': 'parking_lot_4 U car_5'},
 {'nlTask': 'Do not enter street 5 until you reach store 1 as you pick up package 4 from store 1',
  'ltlequ': '!street_5 U store_1&&<>(store_1&&p_package_4)',
  'Spot LTL': '(!street_5 U store_1) & F(p_package_4 & store_1)'},
 {'nlTask': 'Put down anything you hold and go to parking lot 2',
  'ltlequ': '<>(pd&&<>parking_lot_2)',
  'Spot LTL': 'F(pd & Fparking_lot_2)'},
 {'nlTask': 'Pick up bottle 3 from kitchen 2 but do not enter living room 1',
  'ltlequ': '<>(kitchen_2&&p_bottle_3)&&[]!living_room_1',
  'Spot LTL': 'F(kitchen_2 & p_bottle_3) & G!living_room_1'},
 {'nlTask': 'Go to parking lot 5 and stay there',
  'ltlequ': '<>[]parking_lot_5',
  'Spot LTL': 'FGparking_lot_5'},
 {'nlTask': 'Keep visiting charging station 5 and keep taking package 5 from warehouse 1 to store 5',
  'ltlequ': '[]<>charging_station_5&&[]<>(warehouse_1&&<>(p_package_5&&<>(store_5&&pd)))',
  'Spot LTL': 'GFcharging_station_5 & GF(warehouse_1 & F(p_package_5 & F(pd & store_5)))'},
 {'nlTask': 'While never entering park 3, Pick up cone 2 from police station 1 and place it in intersection 2.',
  'ltlequ': '[]!park_3&&<>(police_station_1&&p_cone_2&&<>(intersection_2&&pd))',
  'Spot LTL': 'G!park_3 & F(p_cone_2 & police_station_1 & F(intersection_2 & pd))'},
 {'nlTask': 'Keep visiting street 5',
  'ltlequ': '[]<>street_5',
  'Spot LTL': 'GFstreet_5'},
 {'nlTask': 'Avoid building 1 until street 4 is reached',
  'ltlequ': '!building_1 U street_4',
  'Spot LTL': '!building_1 U street_4'},
 {'nlTask': 'Go to parking lot 2, but never putting anything down',
  'ltlequ': '<>parking_lot_2&&[]!pd',
  'Spot LTL': 'Fparking_lot_2 & G!pd'},
 {'nlTask': 'Go to building 3 and stay there but do not go there until you reach garage 3',
  'ltlequ': '<>[]building_3&&!building_3 U garage_3',
  'Spot LTL': 'FGbuilding_3 & (!building_3 U garage_3)'},
 {'nlTask': 'Never go to street 3',
  'ltlequ': '[]!street_3',
  'Spot LTL': 'G!street_3'},
 {'nlTask': 'Go to statue 5 to take a picture',
  'ltlequ': '<>(statue_5&&photo)',
  'Spot LTL': 'F(photo & statue_5)'},
 {'nlTask': 'Keep going to area 2 and taking a picture',
  'ltlequ': '[]<>(area_2&&photo)',
  'Spot LTL': 'GF(area_2 & photo)'},
 {'nlTask': 'Go to street 5 and then go to building 2 and stay there',
  'ltlequ': '<>(street_5&&<>(building_2&&[]building_2))',
  'Spot LTL': 'F(street_5 & F(building_2 & Gbuilding_2))'},
 {'nlTask': 'Take trash 4 from house 4 to garbage dump 1',
  'ltlequ': '<>(house_4&&<>(p_trash_4&&<>(garbage_dump_1&&pd)))',
  'Spot LTL': 'F(house_4 & F(p_trash_4 & F(garbage_dump_1 & pd)))'},
 {'nlTask': 'Avoid going to garage 1 until you take a picture as you take a picture of landmark 5',
  'ltlequ': '!garage_1 U photo&&<>(landmark_5&&photo)',
  'Spot LTL': '(!garage_1 U photo) & F(landmark_5 & photo)'},
 {'nlTask': 'Place bottle 3 in kitchen 4 after getting it from bedroom 2',
  'ltlequ': '<>(bedroom_2&&<>(p_bottle_3&&<>(kitchen_4&&pd)))',
  'Spot LTL': 'F(bedroom_2 & F(p_bottle_3 & F(kitchen_4 & pd)))'},
 {'nlTask': 'Go to street 5 but avoid parking lot 2',
  'ltlequ': '<>street_5&&[]!parking_lot_2',
  'Spot LTL': 'Fstreet_5 & G!parking_lot_2'},
 {'nlTask': 'Stay in park 1 until you reach table 3',
  'ltlequ': 'park_1 U table_3',
  'Spot LTL': 'park_1 U table_3'},
 {'nlTask': 'Pick up bottle 2 from kitchen 1 and go to hall 2 and stay there',
  'ltlequ': '<>(kitchen_1&&<>(p_bottle_2&&<>(hall_2&&[]hall_2)))',
  'Spot LTL': 'F(kitchen_1 & F(p_bottle_2 & F(hall_2 & Ghall_2)))'},
 {'nlTask': 'Stay away from street 4 until you reach intersection 2 as you go to house 13 and pick up trash 13',
  'ltlequ': '!street_4 U intersection_2&&<>(house_13&&p_trash_13)',
  'Spot LTL': '(!street_4 U intersection_2) & F(house_13 & p_trash_13)'},
 {'nlTask': 'Never enter streets 3 and 4',
  'ltlequ': '[]!(street_3||street_4)',
  'Spot LTL': 'G!(street_3 | street_4)'},
 {'nlTask': 'Keep visiting charger 2 and take plate 4 from table 2 to table 4',
  'ltlequ': '[]<>charger_2&&<>(table_2&&<>(p_plate_4&&<>(table_4&&pd)))',
  'Spot LTL': 'GFcharger_2 & F(table_2 & F(p_plate_4 & F(pd & table_4)))'},
 {'nlTask': 'Pick up document 1 from office 3 and take it to street 2 and stay there',
  'ltlequ': '<>(office_3&&<>(p_document_1&&<>(street_2&&[]street_2)))',
  'Spot LTL': 'F(office_3 & F(p_document_1 & F(street_2 & Gstreet_2)))'},
 {'nlTask': 'Deliver letter 3 to house 2 from post office 1',
  'ltlequ': '<>(post_office_1&&<>(p_letter_3&&<>(house_2&&pd)))',
  'Spot LTL': 'F(post_office_1 & F(p_letter_3 & F(house_2 & pd)))'},
 {'nlTask': 'Take a picture of landmark 6',
  'ltlequ': '<>(landmark_6&&photo)',
  'Spot LTL': 'F(landmark_6 & photo)'},
 {'nlTask': 'Keep visiting street 4',
  'ltlequ': '[]<>street_4',
  'Spot LTL': 'GFstreet_4'},
 {'nlTask': 'Find your way to house 5 and stay there',
  'ltlequ': '<>[]house_5',
  'Spot LTL': 'FGhouse_5'},
 {'nlTask': 'Take a picture of statue 2 but do not go to statue 2 until you reach park 5',
  'ltlequ': '<>(statue_2&&photo)&&!statue_2 U park_5',
  'Spot LTL': 'F(photo & statue_2) & (!statue_2 U park_5)'},
 {'nlTask': 'Never pick up cones 1 or 2',
  'ltlequ': '[]!(p_cone_1||p_cone_2)',
  'Spot LTL': 'G!(p_cone_1 | p_cone_2)'},
 {'nlTask': 'Avoid going to street 4 as you deliver package 8 from store 7 to house 2',
  'ltlequ': '[]!street_4&&<>(store_7&&<>(p_package_8&&<>(house_2&&pd)))',
  'Spot LTL': 'G!street_4 & F(store_7 & F(p_package_8 & F(house_2 & pd)))'},
 {'nlTask': 'Remove cone 5 from parking lot 2 and place it in street 1',
  'ltlequ': '<>(parking_lot_2&&<>(p_cone_5&&<>(street_1&&pd)))',
  'Spot LTL': 'F(parking_lot_2 & F(p_cone_5 & F(pd & street_1)))'},
 {'nlTask': 'Keep picking up trash can 4 from house 2',
  'ltlequ': '[]<>(house_2&&p_trash_can_4)',
  'Spot LTL': 'GF(house_2 & p_trash_can_4)'},
 {'nlTask': 'Never enter house 4',
  'ltlequ': '[]!house_4',
  'Spot LTL': 'G!house_4'},
 {'nlTask': 'Do not go to street 3 as you go to building 4',
  'ltlequ': '[]!street_3&&<>building_4',
  'Spot LTL': 'G!street_3 & Fbuilding_4'},
 {'nlTask': 'Get package 2 from store 3 and take it to house 2 but do not enter mall 1',
  'ltlequ': '<>(store_3&&<>(p_package_2&&<>(house_2&&pd)))&&[]!mall_1',
  'Spot LTL': 'F(store_3 & F(p_package_2 & F(house_2 & pd))) & G!mall_1'},
 {'nlTask': 'Do not ever go to house 3',
  'ltlequ': '[]!house_3',
  'Spot LTL': 'G!house_3'},
 {'nlTask': 'Keep taking a picture of landmark 21',
  'ltlequ': '[]<>(landmark_21&&photo)',
  'Spot LTL': 'GF(landmark_21 & photo)'},
 {'nlTask': 'Go to intersection 5 and stay there',
  'ltlequ': '<>[]intersection_5',
  'Spot LTL': 'FGintersection_5'},
 {'nlTask': 'Take trash can 4 from house 1 to garbage dump 3',
  'ltlequ': '<>(house_1&&<>(p_trash_can_4&&<>(garbage_dump_3&&pd)))',
  'Spot LTL': 'F(house_1 & F(p_trash_can_4 & F(garbage_dump_3 & pd)))'},
 {'nlTask': 'Deliver pass 2 from house 3 to office 2 but do not enter street 5 until you pick up pass 2',
  'ltlequ': '<>(house_3&&<>(p_pass_2&&<>(office_2&&pd)))&&!street_5 U p_pass_2',
  'Spot LTL': 'F(house_3 & F(p_pass_2 & F(office_2 & pd))) & (!street_5 U p_pass_2)'},
 {'nlTask': 'Keep visiting car 3 on your way to building 2',
  'ltlequ': '[]<>car_3&&<>building_2',
  'Spot LTL': 'GFcar_3 & Fbuilding_2'},
 {'nlTask': 'Place letter 2 in building 3 after getting it from post office 1',
  'ltlequ': '<>(post_office_1&&<>(p_lettter_2&&<>(building_3&&pd)))',
  'Spot LTL': 'F(post_office_1 & F(p_lettter_2 & F(building_3 & pd)))'},
 {'nlTask': 'Do not pick up cone 2 until you go to intersection 4',
  'ltlequ': '!p_cone_2 U intersection_4',
  'Spot LTL': '!p_cone_2 U intersection_4'},
 {'nlTask': 'Go to park 8 and stay there',
  'ltlequ': '<>[]park_8',
  'Spot LTL': 'FGpark_8'},
 {'nlTask': 'Do not take a picture until you reach park 5 as you go to take a picture of landmark 4',
  'ltlequ': '!photo U park_5&&<>(landmark_4&&photo)',
  'Spot LTL': '(!photo U park_5) & F(landmark_4 & photo)'},
 {'nlTask': 'Keep taking crate 3 from warehouse 4 to mall 3',
  'ltlequ': '[]<>(warehouse_4&&<>(p_crate_3&&<>(mall_3&&pd)))',
  'Spot LTL': 'GF(warehouse_4 & F(p_crate_3 & F(mall_3 & pd)))'},
 {'nlTask': 'Go to house 2 and pick up trash can 2',
  'ltlequ': '<>(house_2&&p_trash_can_2)',
  'Spot LTL': 'F(house_2 & p_trash_can_2)'},
 {'nlTask': 'Put down what you have and go to park 4 and stay there',
  'ltlequ': '<>(pd&&<>(park_4&&[]park_4))',
  'Spot LTL': 'F(pd & F(park_4 & Gpark_4))'},
 {'nlTask': 'Never touch package 4',
  'ltlequ': '[]!p_package_4',
  'Spot LTL': 'G!p_package_4'},
 {'nlTask': 'Stay in park 5 until you reach bench 4 as you take bottle 5 from store 2 and deliver it to bench 4',
  'ltlequ': 'park_5 U bench_4&&<>(store_2&&<>(p_bottle_5&&<>(bench_4&&pd)))',
  'Spot LTL': '(park_5 U bench_4) & F(store_2 & F(p_bottle_5 & F(bench_4 & pd)))'},
 {'nlTask': 'Deliver package 2 from warehouse 3 to house 1 and take a picture at house 1',
  'ltlequ': '<>(warehouse_3&&<>(p_package_2&&<>(house_1&&pd&&photo)))',
  'Spot LTL': 'F(warehouse_3 & F(p_package_2 & F(house_1 & pd & photo)))'},
 {'nlTask': 'Go to intersection 4 and stay there',
  'ltlequ': '<>[]intersection_4',
  'Spot LTL': 'FGintersection_4'},
 {'nlTask': 'Keep visiting charger 1 as you take box 4 from house 4 to house 9',
  'ltlequ': '[]<>charger_1&&<>(house_4&&<>(box_4&&<>(house_9&&pd)))',
  'Spot LTL': 'GFcharger_1 & F(house_4 & F(box_4 & F(house_9 & pd)))'},
 {'nlTask': 'Take a picture  of intersection 7 and stay there',
  'ltlequ': '<>(intersection_7&&photo&&[]intersection_7)',
  'Spot LTL': 'F(intersection_7 & photo & Gintersection_7)'},
 {'nlTask': 'Take a picture of arch 1',
  'ltlequ': '<>(arch_1&&photo)',
  'Spot LTL': 'F(arch_1 & photo)'},
 {'nlTask': 'Do not go to park 5 until you reach intersection 4',
  'ltlequ': '!park_5 U intersection_4',
  'Spot LTL': '!park_5 U intersection_4'},
 {'nlTask': 'Go to house 4 and pick up package 2 and take it to warehouse 5',
  'ltlequ': '<>(house_4&&<>(p_package_2&&<>(warehouse_5&&pd)))',
  'Spot LTL': 'F(house_4 & F(p_package_2 & F(pd & warehouse_5)))'},
 {'nlTask': 'Go to hotel 3 and stay there',
  'ltlequ': '<>[]hotel_3',
  'Spot LTL': 'FGhotel_3'},
 {'nlTask': 'Pick up luggage 2 and take it to room 402',
  'ltlequ': '<>(p_luggage_2&&<>(room_402&&pd))',
  'Spot LTL': 'F(p_luggage_2 & F(pd & room_402))'},
 {'nlTask': 'Keep visiting building 5',
  'ltlequ': '[]<>building_5',
  'Spot LTL': 'GFbuilding_5'},
 {'nlTask': 'Stay in building 4 until you take folder 3 from room 43 to room 12',
  'ltlequ': 'building_4 U (room_43&&<>(p_folder_3&&<>(room_12&&pd)))',
  'Spot LTL': 'building_4 U (room_43 & F(p_folder_3 & F(pd & room_12)))'},
 {'nlTask': 'Pick up crate 4 and take it to park 1 and stay there',
  'ltlequ': '<>(p_crate_4 && <>(park_1 &&pd&&[]park_1))',
  'Spot LTL': 'F(p_crate_4 & F(park_1 & pd & Gpark_1))'},
 {'nlTask': 'Do not enter park 6 until you pick up pass 4',
  'ltlequ': '!park_6 U p_pass_4',
  'Spot LTL': '!park_6 U p_pass_4'},
 {'nlTask': 'Never go to building 6',
  'ltlequ': '[]!building_6',
  'Spot LTL': 'G!building_6'},
 {'nlTask': 'Never go to street 5 as you pick up box 4 from house 2',
  'ltlequ': '[]!street_5&&<>(house_2&&p_box_4)',
  'Spot LTL': 'G!street_5 & F(house_2 & p_box_4)'},
 {'nlTask': 'Always be in locality 5 as you take package 5 from office 3 to office 6',
  'ltlequ': '[]locality_5&&<>(office_3&&<>(p_package_5&&<>(office_6&&pd)))',
  'Spot LTL': 'Glocality_5 & F(office_3 & F(p_package_5 & F(office_6 & pd)))'},
 {'nlTask': 'Keep visiting charger 5 as you keep taking a picture of region 4',
  'ltlequ': '[]<>charger_5&&[]<>(region_4 && photo)',
  'Spot LTL': 'GFcharger_5 & GF(photo & region_4)'},
 {'nlTask': 'Keep visiting area 5',
  'ltlequ': '[]<>area_5',
  'Spot LTL': 'GFarea_5'},
 {'nlTask': 'Deliver box 4 from house 5 to office 2',
  'ltlequ': '<>(house_5&&<>(p_box_4&&<>(office_2&&pd)))',
  'Spot LTL': 'F(house_5 & F(p_box_4 & F(office_2 & pd)))'},
 {'nlTask': 'Do not go to intersection 5 until you reach street 4 as you take pass 4 from house 4 to office 1',
  'ltlequ': '!intersection_5 U street_4&&<>(house_4&&<>(p_pass_4&&<>(office_1&&pd)))',
  'Spot LTL': '(!intersection_5 U street_4) & F(house_4 & F(p_pass_4 & F(office_1 & pd)))'},
 {'nlTask': 'Go to park 5', 'ltlequ': '<>park_5', 'Spot LTL': 'Fpark_5'},
 {'nlTask': 'Keep delivering crate 8 from mall 5 to office 6',
  'ltlequ': '[]<>(mall_5&&<>(p_crate_8&&<>(office_6&&pd)))',
  'Spot LTL': 'GF(mall_5 & F(p_crate_8 & F(office_6 & pd)))'},
 {'nlTask': 'Stay in parking lot 4 until you take a picture of car 5',
  'ltlequ': 'parking_lot_4 U (car_5&&photo)',
  'Spot LTL': 'parking_lot_4 U (car_5 & photo)'},
 {'nlTask': 'Do not enter building 8 until you reach parking lot 8',
  'ltlequ': '!building_8 U parking_lot_8',
  'Spot LTL': '!building_8 U parking_lot_8'},
 {'nlTask': 'Never pick up crate 8',
  'ltlequ': '[]!p_crate_8',
  'Spot LTL': 'G!p_crate_8'},
 {'nlTask': 'Take a picture of car 1 while never entering street 6',
  'ltlequ': '[]!street_6&&<>(car_1&&photo)',
  'Spot LTL': 'G!street_6 & F(car_1 & photo)'},
 {'nlTask': 'Keep visiting parking lot 4 as you take document 4 from car 5 to car 6',
  'ltlequ': '[]<>parking_lot_4&&<>(car_5&&<>(p_document_4&&<>(car_6&&pd)))',
  'Spot LTL': 'GFparking_lot_4 & F(car_5 & F(p_document_4 & F(car_6 & pd)))'},
 {'nlTask': 'Stay in building 2 until you reach path 3',
  'ltlequ': 'building_2 U path_3',
  'Spot LTL': 'building_2 U path_3'},
 {'nlTask': 'Go to building 9 and stay there, but do not go to building 9 until you reach street 6',
  'ltlequ': '<>[]building_9&&!building_9 U street_6',
  'Spot LTL': 'FGbuilding_9 & (!building_9 U street_6)'},
 {'nlTask': 'Deliver box 8 from store 5 to house 1',
  'ltlequ': '<>(store_5&&<>(p_box_8&&<>(house_1&&pd)))',
  'Spot LTL': 'F(store_5 & F(p_box_8 & F(house_1 & pd)))'},
 {'nlTask': 'Keep taking a picture of intersection 4',
  'ltlequ': '[]<>(intersection_4&&photo)',
  'Spot LTL': 'GF(intersection_4 & photo)'},
 {'nlTask': 'Go to landmark 9 and take a picture and stay there',
  'ltlequ': '<>(landmark_9&&photo&&[]landmark_9)',
  'Spot LTL': 'F(landmark_9 & photo & Glandmark_9)'},
 {'nlTask': 'Do not go to office 4 until you pick pass 6 as you deliver pass 6 from house 5 to office 4',
  'ltlequ': '!office_4 U p_pass_6&&<>(house_5&&<>(p_pass_6&&<>(office_4&&pd)))',
  'Spot LTL': '(!office_4 U p_pass_6) & F(house_5 & F(p_pass_6 & F(office_4 & pd)))'},
 {'nlTask': 'Go to statue 7 and take a picture',
  'ltlequ': '<>(statue_7&&photo)',
  'Spot LTL': 'F(photo & statue_7)'},
 {'nlTask': 'Keep taking crate 8 from warehouse 4 to store 8 and also keep visiting charger 2',
  'ltlequ': '[]<>(warehouse_4&&<>(p_crate_8&&<>(store_8&&pd)))&&[]<>charger_2',
  'Spot LTL': 'GF(warehouse_4 & F(p_crate_8 & F(pd & store_8))) & GFcharger_2'},
 {'nlTask': 'Stay in locality 3 until you reach office 4',
  'ltlequ': 'locality_3 U office_4',
  'Spot LTL': 'locality_3 U office_4'},
 {'nlTask': 'Take letter 4 from office 5 to house 2',
  'ltlequ': '<>(office_5&&<>(p_letter_4&&<>(house_2&&pd)))',
  'Spot LTL': 'F(office_5 & F(p_letter_4 & F(house_2 & pd)))'},
 {'nlTask': 'Do not go to park 3 as you take a picture of monument 3',
  'ltlequ': '[]!park_3&&<>(monument_3&&photo)',
  'Spot LTL': 'G!park_3 & F(monument_3 & photo)'},
 {'nlTask': 'Take a picture of monument 1 but do not go to monument 1 until you reach park 4',
  'ltlequ': '<>(monument_1&&photo)&&!monument_1 U park_4',
  'Spot LTL': 'F(monument_1 & photo) & (!monument_1 U park_4)'},
 {'nlTask': 'Go to street 5 and then go to house 4',
  'ltlequ': '<>(street_5&&<>house_4)',
  'Spot LTL': 'F(street_5 & Fhouse_4)'},
 {'nlTask': 'Stay in house 4 until you reach room 2',
  'ltlequ': 'house_4 U room_2',
  'Spot LTL': 'house_4 U room_2'},
 {'nlTask': 'Never go to house 4 to pick up bottle 2',
  'ltlequ': '[]!(house_4&&p_bottle_2)',
  'Spot LTL': 'G!(house_4 & p_bottle_2)'},
 {'nlTask': 'Stay in area 3', 'ltlequ': '[]area_3', 'Spot LTL': 'Garea_3'},
 {'nlTask': 'Go to mall 5 and stay there',
  'ltlequ': '<>[]mall_5',
  'Spot LTL': 'FGmall_5'},
 {'nlTask': 'Avoid entering parking lot 8 as you go to street 5',
  'ltlequ': '[]!parking_lot_8&&<>street_5',
  'Spot LTL': 'G!parking_lot_8 & Fstreet_5'},
 {'nlTask': 'Keep visiting charger 9 as you keep taking crate 2 from warehouse 8 to store 2',
  'ltlequ': '[]<>charger_9&&[]<>(warehouse_8&&<>(p_crate_2&&<>(store_2&&pd)))',
  'Spot LTL': 'GFcharger_9 & GF(warehouse_8 & F(p_crate_2 & F(pd & store_2)))'},
 {'nlTask': 'Do not go to street 4 until you reach intersection 6 as you go to and stay in street 4',
  'ltlequ': '!street_4 U intersection_6&&<>[]street_4',
  'Spot LTL': '(!street_4 U intersection_6) & FGstreet_4'},
 {'nlTask': 'Deliver box 2 from office 4 to house 1',
  'ltlequ': '<>(office_4&&<>(p_box_2&&<>(house_1&&pd)))',
  'Spot LTL': 'F(office_4 & F(p_box_2 & F(house_1 & pd)))'},
 {'nlTask': 'Avoid landmark 5 until you reach park 5, and eventually take a picture of landmark 5.',
  'ltlequ': '!landmark_5 U park_5&&<>(landmark_5&&photo)',
  'Spot LTL': '(!landmark_5 U park_5) & F(landmark_5 & photo)'},
 {'nlTask': 'Go to park 5 and then take a picture of monument 3',
  'ltlequ': '<>(park_5&&<>(monument_3&&photo))',
  'Spot LTL': 'F(park_5 & F(monument_3 & photo))'},
 {'nlTask': 'Stay in county 4 and keep taking package 4 from office 3 to office 8',
  'ltlequ': '[]county_4&&[]<>(office_3&&<>(p_package_4&&<>(office_8&&pd)))',
  'Spot LTL': 'Gcounty_4 & GF(office_3 & F(p_package_4 & F(office_8 & pd)))'},
 {'nlTask': 'Stay away from intersection 4 until you reach street 5',
  'ltlequ': '!intersection_4 U street_5',
  'Spot LTL': '!intersection_4 U street_5'},
 {'nlTask': 'stay in park 4 until you take the picture of statue 9',
  'ltlequ': 'park_4 U (statue_9&&photo)',
  'Spot LTL': 'park_4 U (photo & statue_9)'},
 {'nlTask': 'Never go to park 5',
  'ltlequ': '[]!park_5',
  'Spot LTL': 'G!park_5'},
 {'nlTask': 'Pick up stack 4 from house 4 and go to street 2 and stay there',
  'ltlequ': '<>(house_4&&<>(p_stack_4&&<>(street_2&&[]street_2)))',
  'Spot LTL': 'F(house_4 & F(p_stack_4 & F(street_2 & Gstreet_2)))'},
 {'nlTask': 'Stay in street 6 until you reach intersection 8',
  'ltlequ': 'street_6 U intersection_8',
  'Spot LTL': 'street_6 U intersection_8'},
 {'nlTask': 'Avoid picking up box 3',
  'ltlequ': '[]!p_box_3',
  'Spot LTL': 'G!p_box_3'},
 {'nlTask': 'Keep taking crate 1 from storage 4 to office 2',
  'ltlequ': '[]<>(storage_4&&<>(p_crate_1&&<>(office_2&&pd)))',
  'Spot LTL': 'GF(storage_4 & F(p_crate_1 & F(office_2 & pd)))'},
 {'nlTask': 'Stay in area 5', 'ltlequ': '[]area_5', 'Spot LTL': 'Garea_5'},
 {'nlTask': 'Keep taking a picture of area 51 while you also keep visiting charger 4',
  'ltlequ': '[]<>(area_51&&photo)&&[]<>charger_4',
  'Spot LTL': 'GF(area_51 & photo) & GFcharger_4'},
 {'nlTask': 'Avoid going to store 4 until you reach street 6 as you take package 8 from office 2 to store 4',
  'ltlequ': '!store_4 U street_6&&<>(office_2&&<>(p_package_8&&<>(store_4&&pd)))',
  'Spot LTL': '(!store_4 U street_6) & F(office_2 & F(p_package_8 & F(pd & store_4)))'},
 {'nlTask': 'Keep taking images of locality 7, while you never go to park 3',
  'ltlequ': '[]<>(locality_7&&photo)&&[]!park_3',
  'Spot LTL': 'GF(locality_7 & photo) & G!park_3'},

In [190]:
df = pd.json_normalize(d).rename(columns={'ltlequ': 'original LTL', 'nlTask': 'original NL'})
df['APs'] = df['Spot LTL'].apply(lambda x: extract_atomic_propositions(x))
df['ap_NL'] = df.apply(
    lambda row: swap_row_propositions(row, 'APs', 'original NL'), 
    axis=1
)
df['dict_AP']=df['APs'].apply(lambda x: {x.removeprefix('p_').replace('_', ' ') : x for x in x})

def dynamic_replace(row):
    text = row['ap_NL']
    mapping = row['dict_AP']
    
    if not mapping or not isinstance(mapping, dict):
        return text
    
    # Create a regex pattern from the keys of the row's dictionary
    # \b ensures we only match whole words
    pattern = re.compile(r'\b(' + '|'.join(re.escape(k) for k in mapping.keys()) + r')\b')
    
    # Replace using the dictionary values
    return pattern.sub(lambda m: mapping[m.group(0)], text)

df['ap_NL'] = df.apply(dynamic_replace, axis=1)
df.to_csv('./processed_data/ConformalNL2LTL/processed_data.csv', index=False, sep=';')
df

,original NL,original LTL,Spot LTL,APs,ap_NL,dict_AP
0,Take a picture of building 2,<>(building_2&&photo),F(building_2 & photo),"[photo, building_2]",Take a picture of building_2,"{'photo': 'photo', 'building 2': 'building_2'}"
1,Take bottle 3 from store 1 and put it in hospi...,<>(shop_1&&<>(p_bottle_3&&<>(hospital_2&&pd))),F(shop_1 & F(p_bottle_3 & F(hospital_2 & pd))),"[pd, p_bottle_3, shop_1, hospital_2]",Take p_bottle_3 from store 1 and put it in hos...,"{'pd': 'pd', 'bottle 3': 'p_bottle_3', 'shop 1..."
2,Go to parking lot 2 and pick up dish 2,<>(parking_lot_2&&p_dish_2),F(p_dish_2 & parking_lot_2),"[p_dish_2, parking_lot_2]",Go to parking_lot_2 and pick up p_dish_2,"{'dish 2': 'p_dish_2', 'parking lot 2': 'parki..."
3,Go to hospital 3 and pick up water bottle 4 wh...,<>(hospital_3&&p_bottle_4)&&[]!pharmacy_2,F(hospital_3 & p_bottle_4) & G!pharmacy_2,"[p_bottle_4, hospital_3, pharmacy_2]",Go to hospital_3 and pick up water p_bottle_4 ...,"{'bottle 4': 'p_bottle_4', 'hospital 3': 'hosp..."
4,Stay in parking lot 4 until you reach car 5,parking_lot_4 U car_5,parking_lot_4 U car_5,"[parking_lot_4, car_5]",Stay in parking_lot_4 until you reach car_5,"{'parking lot 4': 'parking_lot_4', 'car 5': 'c..."
...,...,...,...,...,...,...
995,Persistently taking crate 6 to building 5 afte...,[]<>(store_2&&<>(p_crate_6&&<>(building_5&&pd))),GF(store_2 & F(p_crate_6 & F(building_5 & pd))),"[pd, building_5, p_crate_6, store_2]",Persistently taking p_crate_6 to building_5 af...,"{'pd': 'pd', 'building 5': 'building_5', 'crat..."
996,"Deliver box 1 from store 6 to house 9, then pr...",<>(store_6&&<>(p_box_1&&<>(house_9&&pd)))&&<>(...,F(store_6 & F(p_box_1 & F(house_9 & pd))) & F(...,"[pd, house_9, intersection_5, p_box_1, store_6]","Deliver p_box_1 from store_6 to house_9, then ...","{'pd': 'pd', 'house 9': 'house_9', 'intersecti..."
997,Ensure you transport box 1 from store 6 to hou...,<>(store_6&&<>(p_box_1&&<>(house_9&&pd)))&&<>(...,F(store_6 & F(p_box_1 & F(house_9 & pd))) & F(...,"[pd, house_9, intersection_5, p_box_1, store_6]",Ensure you transport p_box_1 from store_6 to h...,"{'pd': 'pd', 'house 9': 'house_9', 'intersecti..."
998,"Move box 1 from store 6 to house 9, and then g...",<>(store_6&&<>(p_box_1&&<>(house_9&&pd)))&&<>(...,F(store_6 & F(p_box_1 & F(house_9 & pd))) & F(...,"[pd, house_9, intersection_5, p_box_1, store_6]","Move p_box_1 from store_6 to house_9, and then...","{'pd': 'pd', 'house 9': 'house_9', 'intersecti..."
999,"Pick up box 1 from store 6, deliver it to hous...",<>(store_6&&<>(p_box_1&&<>(house_9&&pd)))&&<>(...,F(store_6 & F(p_box_1 & F(house_9 & pd))) & F(...,"[pd, house_9, intersection_5, p_box_1, store_6]","Pick up p_box_1 from store_6, deliver it to ho...","{'pd': 'pd', 'house 9': 'house_9', 'intersecti..."