In [123]:
import pandas as pd

import os
path2data = './raw_data/NL to LTL Synthetic Dataset'
data = os.listdir(path2data)
data = [x for x in data if (  ("train" in x and 'unrestricted' in x and "~" not in x) )]
data

['unrestricted_train_dataset-50.csv', 'unrestricted_train_dataset-140.csv']

In [124]:
import spot
def simplify_formula(formula_str):

    f = spot.formula(formula_str)
    return f


def extract_atomic_propositions(formula_str):
    f = spot.formula(formula_str)
    aps = spot.atomic_prop_collect(f)
    
    mapping = []
    for i, atom in enumerate(aps):
        mapping.append(str(atom))
        

    return mapping

In [125]:
lista = []
for elem in data:
    df = pd.read_csv(path2data + '/' + elem)[['ltl','en']]
    df['source'] = str(elem)
    lista.append( df )
result = pd.concat(lista, ignore_index=True)
result

,ltl,en,source
0,G(!( brake_is_pressed | house_is_open | train_...,under no circumstances either the brake is pre...,unrestricted_train_dataset-50.csv
1,G(!( car_starts | semaphore_is_red | bar_is_up )),"under no condition either a car starts, a sema...",unrestricted_train_dataset-50.csv
2,G(!( escalator_speeds_up & train_derails & hou...,"under no condition the escalator speeds up, th...",unrestricted_train_dataset-50.csv
3,G(!( constructor_instantiate_objects & bar_is_...,it is never the case that a constructor instan...,unrestricted_train_dataset-50.csv
4,G(!( table_has_been_moved & table_is_brown & m...,it never happens that the table has been moved...,unrestricted_train_dataset-50.csv
...,...,...,...
189995,G(( elevator_rises ) -> G(( sensor_captures_da...,each time the elevator rises then always when ...,unrestricted_train_dataset-140.csv
189996,G(( train_derails ) -> G(( escalator_moves ) -...,when the train derails then it will happen tha...,unrestricted_train_dataset-140.csv
189997,G(( brake_is_pressed ) -> G(( constructor_inst...,the brake is pressed involves that whenever th...,unrestricted_train_dataset-140.csv
189998,G(( elevator_is_blocked ) -> G(( sensor_captur...,when the elevator is blocked then if the senso...,unrestricted_train_dataset-140.csv
189999,G(( house_collapses ) -> G(( semaphore_is_gree...,a house collapses involves that every time the...,unrestricted_train_dataset-140.csv

In [126]:
result = result.rename(columns={'ltl': 'original LTL', 'en': 'original NL'})

result

,original LTL,original NL,source
0,G(!( brake_is_pressed | house_is_open | train_...,under no circumstances either the brake is pre...,unrestricted_train_dataset-50.csv
1,G(!( car_starts | semaphore_is_red | bar_is_up )),"under no condition either a car starts, a sema...",unrestricted_train_dataset-50.csv
2,G(!( escalator_speeds_up & train_derails & hou...,"under no condition the escalator speeds up, th...",unrestricted_train_dataset-50.csv
3,G(!( constructor_instantiate_objects & bar_is_...,it is never the case that a constructor instan...,unrestricted_train_dataset-50.csv
4,G(!( table_has_been_moved & table_is_brown & m...,it never happens that the table has been moved...,unrestricted_train_dataset-50.csv
...,...,...,...
189995,G(( elevator_rises ) -> G(( sensor_captures_da...,each time the elevator rises then always when ...,unrestricted_train_dataset-140.csv
189996,G(( train_derails ) -> G(( escalator_moves ) -...,when the train derails then it will happen tha...,unrestricted_train_dataset-140.csv
189997,G(( brake_is_pressed ) -> G(( constructor_inst...,the brake is pressed involves that whenever th...,unrestricted_train_dataset-140.csv
189998,G(( elevator_is_blocked ) -> G(( sensor_captur...,when the elevator is blocked then if the senso...,unrestricted_train_dataset-140.csv
189999,G(( house_collapses ) -> G(( semaphore_is_gree...,a house collapses involves that every time the...,unrestricted_train_dataset-140.csv

In [127]:

result['Spot LTL'] = result['original LTL'].apply(lambda x: str(simplify_formula(x)))
result['APs'] = result['original LTL'].apply(lambda x: extract_atomic_propositions(x))
result

,original LTL,original NL,source,Spot LTL,APs
0,G(!( brake_is_pressed | house_is_open | train_...,under no circumstances either the brake is pre...,unrestricted_train_dataset-50.csv,G!(brake_is_pressed | house_is_open | train_is...,"[brake_is_pressed, house_is_open, train_is_cro..."
1,G(!( car_starts | semaphore_is_red | bar_is_up )),"under no condition either a car starts, a sema...",unrestricted_train_dataset-50.csv,G!(bar_is_up | car_starts | semaphore_is_red),"[car_starts, semaphore_is_red, bar_is_up]"
2,G(!( escalator_speeds_up & train_derails & hou...,"under no condition the escalator speeds up, th...",unrestricted_train_dataset-50.csv,G!(escalator_speeds_up & house_is_built & trai...,"[escalator_speeds_up, train_derails, house_is_..."
3,G(!( constructor_instantiate_objects & bar_is_...,it is never the case that a constructor instan...,unrestricted_train_dataset-50.csv,G!(bar_is_closing & constructor_instantiate_ob...,"[constructor_instantiate_objects, bar_is_closi..."
4,G(!( table_has_been_moved & table_is_brown & m...,it never happens that the table has been moved...,unrestricted_train_dataset-50.csv,G!(manager_collect_claims & table_has_been_mov...,"[table_has_been_moved, table_is_brown, manager..."
...,...,...,...,...,...
189995,G(( elevator_rises ) -> G(( sensor_captures_da...,each time the elevator rises then always when ...,unrestricted_train_dataset-140.csv,G(elevator_rises -> G(sensor_captures_data -> ...,"[train_is_crossing, sensor_captures_data, elev..."
189996,G(( train_derails ) -> G(( escalator_moves ) -...,when the train derails then it will happen tha...,unrestricted_train_dataset-140.csv,G(train_derails -> G(escalator_moves -> Feleva...,"[train_derails, escalator_moves, elevator_is_b..."
189997,G(( brake_is_pressed ) -> G(( constructor_inst...,the brake is pressed involves that whenever th...,unrestricted_train_dataset-140.csv,G(brake_is_pressed -> G(constructor_instantiat...,"[brake_is_pressed, constructor_instantiate_obj..."
189998,G(( elevator_is_blocked ) -> G(( sensor_captur...,when the elevator is blocked then if the senso...,unrestricted_train_dataset-140.csv,G(elevator_is_blocked -> G(sensor_captures_dat...,"[sensor_captures_data, elevator_is_blocked, tr..."
189999,G(( house_collapses ) -> G(( semaphore_is_gree...,a house collapses involves that every time the...,unrestricted_train_dataset-140.csv,G(house_collapses -> G(semaphore_is_green -> F...,"[table_is_brown, house_collapses, semaphore_is..."

In [128]:
import re
def swap_row_propositions(row, prop_col, text_col):
    propositions = row[prop_col]
    text = row[text_col]
    
    if not isinstance(propositions, list) or not isinstance(text, str):
        return text

    # 1. Create mapping for THIS row: {'car starts': 'car_starts'}
    mapping = {p.replace('_', ' '): p for p in propositions}
    
    # 2. Build a regex pattern from these specific keys
    # Sort by length descending to match longest phrases first
    sorted_keys = sorted(mapping.keys(), key=len, reverse=True)
    pattern = re.compile(r'\b(' + '|'.join(map(re.escape, sorted_keys)) + r')\b')
    
    # 3. Replace matches in the text using the mapping
    return pattern.sub(lambda m: mapping[m.group(0)], text)

# Apply the function across the rows
result['ap_NL'] = result.apply(
    lambda row: swap_row_propositions(row, 'APs', 'original NL'), 
    axis=1
)

In [129]:
result

,original LTL,original NL,source,Spot LTL,APs,ap_NL
0,G(!( brake_is_pressed | house_is_open | train_...,under no circumstances either the brake is pre...,unrestricted_train_dataset-50.csv,G!(brake_is_pressed | house_is_open | train_is...,"[brake_is_pressed, house_is_open, train_is_cro...",under no circumstances either the brake_is_pre...
1,G(!( car_starts | semaphore_is_red | bar_is_up )),"under no condition either a car starts, a sema...",unrestricted_train_dataset-50.csv,G!(bar_is_up | car_starts | semaphore_is_red),"[car_starts, semaphore_is_red, bar_is_up]","under no condition either a car_starts, a sema..."
2,G(!( escalator_speeds_up & train_derails & hou...,"under no condition the escalator speeds up, th...",unrestricted_train_dataset-50.csv,G!(escalator_speeds_up & house_is_built & trai...,"[escalator_speeds_up, train_derails, house_is_...","under no condition the escalator_speeds_up, th..."
3,G(!( constructor_instantiate_objects & bar_is_...,it is never the case that a constructor instan...,unrestricted_train_dataset-50.csv,G!(bar_is_closing & constructor_instantiate_ob...,"[constructor_instantiate_objects, bar_is_closi...",it is never the case that a constructor_instan...
4,G(!( table_has_been_moved & table_is_brown & m...,it never happens that the table has been moved...,unrestricted_train_dataset-50.csv,G!(manager_collect_claims & table_has_been_mov...,"[table_has_been_moved, table_is_brown, manager...",it never happens that the table_has_been_moved...
...,...,...,...,...,...,...
189995,G(( elevator_rises ) -> G(( sensor_captures_da...,each time the elevator rises then always when ...,unrestricted_train_dataset-140.csv,G(elevator_rises -> G(sensor_captures_data -> ...,"[train_is_crossing, sensor_captures_data, elev...",each time the elevator_rises then always when ...
189996,G(( train_derails ) -> G(( escalator_moves ) -...,when the train derails then it will happen tha...,unrestricted_train_dataset-140.csv,G(train_derails -> G(escalator_moves -> Feleva...,"[train_derails, escalator_moves, elevator_is_b...",when the train_derails then it will happen tha...
189997,G(( brake_is_pressed ) -> G(( constructor_inst...,the brake is pressed involves that whenever th...,unrestricted_train_dataset-140.csv,G(brake_is_pressed -> G(constructor_instantiat...,"[brake_is_pressed, constructor_instantiate_obj...",the brake_is_pressed involves that whenever th...
189998,G(( elevator_is_blocked ) -> G(( sensor_captur...,when the elevator is blocked then if the senso...,unrestricted_train_dataset-140.csv,G(elevator_is_blocked -> G(sensor_captures_dat...,"[sensor_captures_data, elevator_is_blocked, tr...",when the elevator_is_blocked then if the senso...
189999,G(( house_collapses ) -> G(( semaphore_is_gree...,a house collapses involves that every time the...,unrestricted_train_dataset-140.csv,G(house_collapses -> G(semaphore_is_green -> F...,"[table_is_brown, house_collapses, semaphore_is...",a house_collapses involves that every time the...

In [130]:
result.to_csv('./processed_data/NL to LTL Synthetic Dataset/processed_data.csv', index=False, sep=';')

In [ ]:
def english_to_ltl(s):
    s = s.replace('globally', 'G')
    s = s.replace('finally', 'F')
    s = s.replace('next', 'X')
    s = s.replace('or', '|')
    s = s.replace('double_implies', '<->')
    s = s.replace('implies', '->')
    s = s.replace('and', '&')
    s = s.replace('not', '!')
    s = s.replace('negation', '!')
    s = s.replace('implies', '->')
    return s

In [135]:
path2data = './raw_data/VLTL-Bench/new/'
data = os.listdir(path2data)
data = [x for x in data ]
data

['search_and_rescue.jsonl', 'traffic_light.jsonl', 'warehouse.jsonl']

In [137]:
df = {}
for file in data:
    df[file] = pd.read_json(os.path.join(path2data, file), lines=True)

reserved = ['globally', 'finally', 'next', 'or', 'double_implies', 
            'implies', 'and', 'until', 'not', '(', ')']

def wrap_propositions(token_list):
    return [f'"{item}"' if item not in reserved else item for item in token_list]


for file in df:
    df[file]['source'] = file
    df[file]['original NL'] = df[file]['sentence'].str.join(' ')
    df[file]['tl'] = df[file]['tl'].apply(wrap_propositions)
    df[file]['original LTL'] = df[file]['tl'].str.join(' ').replace('""', '"', regex=True)
    df[file]['Spot LTL'] = df[file]['original LTL'].apply(english_to_ltl)

def get_flat_map(nested_dict):
    # We combine all args_canon -> args_ref pairs into one dict
    if not isinstance(nested_dict, dict):
        return {}
    
    flat_map = {}
    for prop in nested_dict.values():
        # Zip canon keys to ref values and update our master map
        flat_map.update(zip(prop.get('args_ref', []), prop.get('args_canon', [])))
    return flat_map

for file in df:
    df[file]['AP_dict'] = df[file]['prop_dict'].apply(lambda x: {x[y]['action_ref']: x[y]['action_canon'] for y in x})
    
    df[file]['AP_misc_dict'] = df[file]['prop_dict'].apply(get_flat_map)
    df[file]['merged_dict'] = df[file].apply(lambda row: row['AP_misc_dict'] | row['AP_dict'], axis=1)

def replace_from_mapping(row, text_column):
    text = str(row[text_column])
    mapping = row['merged_dict']
    
    # Iterate through the dictionary for this specific row
    for old_val, new_val in mapping.items():
        # replace() handles all instances of that key in the string
        text = text.replace(old_val, new_val)
    
    return text

import csv

for file in df:
    # Apply the function to your text column
    # Replace 'my_text_col' with the actual name of your string column
    df[file]['original NL'] = df[file].apply(replace_from_mapping, axis=1, text_column='original NL')
    df[file]['Spot LTL'] = df[file]['Spot LTL'].apply(lambda x: str(simplify_formula(x)))
    df[file]['APs'] = df[file]['Spot LTL'].apply(lambda x: extract_atomic_propositions(x))
    df[file][['source','APs','original NL','original LTL','Spot LTL']].to_csv('./processed_data/VLTL-Bench/new/'+file.split('.')[0]+'.csv', index=False, sep=';',index_label=False, quoting=csv.QUOTE_MINIMAL)
#

In [138]:
path2data = './raw_data/VLTL-Bench/prev/'
data = os.listdir(path2data)
data = [x for x in data ]
data

['GLTL.jsonl', 'navi.jsonl', 'conformal.jsonl', 'cleanup_world.jsonl']

In [ ]:
df = {}
for file in data:
    df[file] = pd.read_json(os.path.join(path2data, file), lines=True)

reserved = ['globally', 'finally', 'next', 'or', 'double_implies', 
            'implies', 'and', 'until', 'not', 'negation', '(', ')']

def wrap_propositions(token_list):
    return [f'"{item}"' if item not in reserved else item for item in token_list]


for file in df:
    df[file]['source'] = file
    df[file]['original NL'] = df[file]['sentence'].str.join(' ')
    df[file]['tl'] = df[file]['tl'].apply(wrap_propositions)
    df[file]['original LTL'] = df[file]['tl'].str.join(' ').replace('""', '"', regex=True)
    df[file]['Spot LTL'] = df[file]['original LTL'].apply(english_to_ltl)

def get_flat_map(nested_dict):
    # We combine all args_canon -> args_ref pairs into one dict
    if not isinstance(nested_dict, dict):
        return {}
    
    flat_map = {}
    for prop in nested_dict.values():
        # Zip canon keys to ref values and update our master map
        flat_map.update(zip(prop.get('args_ref', []), prop.get('args_canon', [])))
    return flat_map

for file in df:
    df[file]['AP_dict'] = df[file]['prop_dict'].apply(lambda x: {x[y]['action_ref']: x[y]['action_canon'] for y in x})
    
    df[file]['AP_misc_dict'] = df[file]['prop_dict'].apply(get_flat_map)
    df[file]['merged_dict'] = df[file].apply(lambda row: row['AP_misc_dict'] | row['AP_dict'], axis=1)

def replace_from_mapping(row, text_column):
    text = str(row[text_column])
    mapping = row['merged_dict']
    
    # Iterate through the dictionary for this specific row
    for old_val, new_val in mapping.items():
        # replace() handles all instances of that key in the string
        text = text.replace(old_val, new_val)
    
    return text

import csv

for file in df:
    # Apply the function to your text column
    # Replace 'my_text_col' with the actual name of your string column
    df[file]['original NL'] = df[file].apply(replace_from_mapping, axis=1, text_column='original NL')
    df[file]['Spot LTL'] = df[file]['Spot LTL'].apply(lambda x: str(simplify_formula(x)))
    df[file]['APs'] = df[file]['Spot LTL'].apply(lambda x: extract_atomic_propositions(x))
    df[file][['source','APs','original NL','original LTL','Spot LTL']].to_csv('./processed_data/VLTL-Bench/prev/'+file.split('.')[0]+'.csv', index=False, sep=';',index_label=False, quoting=csv.QUOTE_MINIMAL)
#

parse_error:
>>> "negation" ( "let_go(pear)" ) "imply" "venture_to(trash_can)"
               ^
syntax error, unexpected opening parenthesis

>>> "negation" ( "let_go(pear)" ) "imply" "venture_to(trash_can)"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ignoring trailing garbage

In [142]:
df[file].T[0]['tl']

['"negation"',
 '(',
 '"let_go(pear)"',
 ')',
 '"imply"',
 '"venture_to(trash_can)"']

In [288]:
import json
from pprint import pprint

with open('./raw_data/ConformalNL2LTL/final_calib.json') as json_data:
    d = json.load(json_data)
    json_data.close()

for ind in range(len(d)):
    d[ind]['ltlequ'] = d[ind]['ltlequ'][0][:-1]
    if "U" in d[ind]['ltlequ']:
       d[ind]['ltlequ'] = d[ind]['ltlequ'].replace("U", " U ")
    
    d[ind]['Spot LTL'] = str(simplify_formula(str(d[ind]['ltlequ'])))

d

[{'nlTask': 'Do not enter garage 1 until you take a picture of landmark 5',
  'ltlequ': '!garage_1 U (landmark_5&&photo)',
  'Spot LTL': '!garage_1 U (landmark_5 & photo)'},
 {'nlTask': 'Ensure you never retrieve package 5',
  'ltlequ': '[]!p_package_5',
  'Spot LTL': 'G!p_package_5'},
 {'nlTask': 'Do not go to street 7 while you take package 3 from store 9 to house 1',
  'ltlequ': '[]!street_7&&<>(store_9&&<>(p_package_3&&<>(house_1&&pd)))',
  'Spot LTL': 'G!street_7 & F(store_9 & F(p_package_3 & F(house_1 & pd)))'},
 {'nlTask': 'Start by visiting mall 5 to pick up box 4, and then move it to house 1',
  'ltlequ': '<>(mall_5&&<>(p_box_4&&<>(house_1&&pd)))',
  'Spot LTL': 'F(mall_5 & F(p_box_4 & F(house_1 & pd)))'},
 {'nlTask': 'Do not go to intersection 1 before arriving at street 6, and ensure you take cone 3 from street 2 and place it in intersection 1',
  'ltlequ': '!intersection_1 U street_6&&<>(street_2&&<>(p_cone_3&&<>(intersection_1&&pd)))',
  'Spot LTL': '(!intersection_1 U street_6) & F(street_2 & F(p_cone_3 & F(intersection_1 & pd)))'},
 {'nlTask': 'Never pick up package 5',
  'ltlequ': '[]!p_package_5',
  'Spot LTL': 'G!p_package_5'},
 {'nlTask': 'Stay within street 8 at all times',
  'ltlequ': '[]street_8',
  'Spot LTL': 'Gstreet_8'},
 {'nlTask': 'Always stay away from parking lot 5 while ensuring you take a picture of car 3',
  'ltlequ': '[]!parking_lot_5&&<>(car_3&&photo)',
  'Spot LTL': 'G!parking_lot_5 & F(car_3 & photo)'},
 {'nlTask': 'Always be in locality 5 as you take package 5 from office 3 to office 6',
  'ltlequ': '[]locality_5&&<>(office_3&&<>(p_package_5&&<>(office_6&&pd)))',
  'Spot LTL': 'Glocality_5 & F(office_3 & F(p_package_5 & F(office_6 & pd)))'},
 {'nlTask': 'Visit statue 5 and take a picture of it',
  'ltlequ': '<>(statue_5&&photo)',
  'Spot LTL': 'F(photo & statue_5)'},
 {'nlTask': 'Ensure you repeatedly take a picture of intersection 4 over time',
  'ltlequ': '[]<>(intersection_4&&photo)',
  'Spot LTL': 'GF(intersection_4 & photo)'},
 {'nlTask': 'Keep staying within street 5 while regularly photographing parking lot 4',
  'ltlequ': '[]street_5&&[]<>(parking_lot_4&&photo)',
  'Spot LTL': 'Gstreet_5 & GF(parking_lot_4 & photo)'},
 {'nlTask': 'Stay in area 3', 'ltlequ': '[]area_3', 'Spot LTL': 'Garea_3'},
 {'nlTask': 'Stay away from room 2 until you collect bottle 4 from kitchen 1 and deliver it to table 4',
  'ltlequ': '!room_2 U (kitchen_1&&<>(p_bottle_4&&<>(table_4&&pd)))',
  'Spot LTL': '!room_2 U (kitchen_1 & F(p_bottle_4 & F(pd & table_4)))'},
 {'nlTask': 'Pick up trash can 4 from house 1 and deliver it to gabage dump 3',
  'ltlequ': '<>(house_1&&<>(p_trash_can_4&&<>(garbage_dump_3&&pd)))',
  'Spot LTL': 'F(house_1 & F(p_trash_can_4 & F(garbage_dump_3 & pd)))'},
 {'nlTask': 'Avoid entering parking lot 8 as you go to street 5',
  'ltlequ': '[]!parking_lot_8&&<>street_5',
  'Spot LTL': 'G!parking_lot_8 & Fstreet_5'},
 {'nlTask': 'Do not enter park 5 until you reach intersection 5 as you take a picture of monument 3',
  'ltlequ': '!park_5 U intersection_5&&<>(monument_3&&photo)',
  'Spot LTL': '(!park_5 U intersection_5) & F(monument_3 & photo)'},
 {'nlTask': 'Ensure you never go into park 2',
  'ltlequ': '[]!park_2',
  'Spot LTL': 'G!park_2'},
 {'nlTask': 'Do not go to intersection 5 until you reach street 4 as you take pass 4 from house 4 to office 1',
  'ltlequ': '!intersection_5 U street_4&&<>(house_4&&<>(p_pass_4&&<>(office_1&&pd)))',
  'Spot LTL': '(!intersection_5 U street_4) & F(house_4 & F(p_pass_4 & F(office_1 & pd)))'},
 {'nlTask': 'Repeatedly take brochure 8 from table 2 to street 9 while consistently visiting charger 6',
  'ltlequ': '[]<>(table_2&&<>(p_brochure_8&&<>(street_9&&pd)))&&[]<>charger_6',
  'Spot LTL': 'GF(table_2 & F(p_brochure_8 & F(pd & street_9))) & GFcharger_6'},
 {'nlTask': 'Do not collect cone 2 before going to intersection 4',
  'ltlequ': '!p_cone_2 U intersection_4',
  'Spot LTL': '!p_cone_2 U intersection_4'},
 {'nlTask': 'Avoid picking up box 3',
  'ltlequ': '[]!p_box_3',
  'Spot LTL': 'G!p_box_3'},
 {'nlTask': 'Stay away from park 5 until you arrive at intersection 5, and afterward, take a picture of monument 3',
  'ltlequ': '!park_5 U intersection_5&&<>(monument_3&&photo)',
  'Spot LTL': '(!park_5 U intersection_5) & F(monument_3 & photo)'},
 {'nlTask': 'Eventually go to park 5',
  'ltlequ': '<>park_5',
  'Spot LTL': 'Fpark_5'},
 {'nlTask': 'Keep taking pictures of car 1 but never enter parking lot 9',
  'ltlequ': '[]<>(car_1&&photo)&&[]!parking_lot_9',
  'Spot LTL': 'GF(car_1 & photo) & G!parking_lot_9'},
 {'nlTask': 'Ensure you visit park 5',
  'ltlequ': '<>park_5',
  'Spot LTL': 'Fpark_5'},
 {'nlTask': 'Keep visiting building 5',
  'ltlequ': '[]<>building_5',
  'Spot LTL': 'GFbuilding_5'},
 {'nlTask': 'Avoid entering park 4 until you reach street 3, and then transport takeout 2 from store 7 to bench 3',
  'ltlequ': '!park_4 U street_3&&<>(store_7&&<>(p_takeout_2&&<>(bench_3&&pd)))',
  'Spot LTL': '(!park_4 U street_3) & F(store_7 & F(p_takeout_2 & F(bench_3 & pd)))'},
 {'nlTask': 'Keep photographing statue 4 while ensuring you also keep revisiting charger 4',
  'ltlequ': '[]<>(statue_4&&photo)&&[]<>charger_4',
  'Spot LTL': 'GF(photo & statue_4) & GFcharger_4'},
 {'nlTask': 'Pick up dish 2 from parking lot 2',
  'ltlequ': '<>(parking_lot_2&&p_dish_2)',
  'Spot LTL': 'F(p_dish_2 & parking_lot_2)'},
 {'nlTask': 'Eventually, you need to visit bench 4, capture a photo, and stay there permanently',
  'ltlequ': '<>(bench_4&&photo&&[]bench_4)',
  'Spot LTL': 'F(bench_4 & photo & Gbench_4)'},
 {'nlTask': 'Do not go to landmark 5 before reaching park 5, and ensure you eventually take a picture of landmark 5',
  'ltlequ': '!landmark_5 U park_5&&<>(landmark_5&&photo)',
  'Spot LTL': '(!landmark_5 U park_5) & F(landmark_5 & photo)'},
 {'nlTask': 'Retrieve trash can 4 at house 1 and move it to garbage dump 3',
  'ltlequ': '<>(house_1&&<>(p_trash_can_4&&<>(garbage_dump_3&&pd)))',
  'Spot LTL': 'F(house_1 & F(p_trash_can_4 & F(garbage_dump_3 & pd)))'},
 {'nlTask': 'Repeatedly transport brochure 8 from table 2 to street 9 while repeatedly visiting charger 6',
  'ltlequ': '[]<>(table_2&&<>(p_brochure_8&&<>(street_9&&pd)))&&[]<>charger_6',
  'Spot LTL': 'GF(table_2 & F(p_brochure_8 & F(pd & street_9))) & GFcharger_6'},
 {'nlTask': 'Keep visiting charger 2 and take plate 4 from table 2 to table 4',
  'ltlequ': '[]<>charger_2&&<>(table_2&&<>(p_plate_4&&<>(table_4&&pd)))',
  'Spot LTL': 'GFcharger_2 & F(table_2 & F(p_plate_4 & F(pd & table_4)))'},
 {'nlTask': 'Remain in parking lot 5 until you capture a photo of car 5',
  'ltlequ': 'parking_lot_5 U (car_5&&photo)',
  'Spot LTL': 'parking_lot_5 U (car_5 & photo)'},
 {'nlTask': 'Keep delivering crate 8 from mall 5 to office 6',
  'ltlequ': '[]<>(mall_5&&<>(p_crate_8&&<>(office_6&&pd)))',
  'Spot LTL': 'GF(mall_5 & F(p_crate_8 & F(office_6 & pd)))'},
 {'nlTask': 'Stay in park 8 until you take a picture of monument 2 and then go to bench 5 and stay there',
  'ltlequ': 'park_8 U (monument_2&&photo&&<>(bench_5&&[]bench_5))',
  'Spot LTL': 'park_8 U (monument_2 & photo & F(bench_5 & Gbench_5))'},
 {'nlTask': 'Stay within park 4 until you capture a picture of statue 9',
  'ltlequ': 'park_4 U (statue_9&&photo)',
  'Spot LTL': 'park_4 U (photo & statue_9)'},
 {'nlTask': 'Go to statue 5 to take a picture',
  'ltlequ': '<>(statue_5&&photo)',
  'Spot LTL': 'F(photo & statue_5)'},
 {'nlTask': 'First go to park 5 and then make sure to photograph monument 3',
  'ltlequ': '<>(park_5&&<>(monument_3&&photo))',
  'Spot LTL': 'F(park_5 & F(monument_3 & photo))'},
 {'nlTask': 'Keep taking crate 3 from warehouse 4 to mall 3',
  'ltlequ': '[]<>(warehouse_4&&<>(p_crate_3&&<>(mall_3&&pd)))',
  'Spot LTL': 'GF(warehouse_4 & F(p_crate_3 & F(mall_3 & pd)))'},
 {'nlTask': 'Go to mall 5 and stay there',
  'ltlequ': '<>[]mall_5',
  'Spot LTL': 'FGmall_5'},
 {'nlTask': 'Avoid going to store 4 until you reach street 6 as you take package 8 from office 2 to store 4',
  'ltlequ': '!store_4 U street_6&&<>(office_2&&<>(p_package_8&&<>(store_4&&pd)))',
  'Spot LTL': '(!store_4 U street_6) & F(office_2 & F(p_package_8 & F(pd & store_4)))'},
 {'nlTask': 'Stay out of locality 5 until you retrieve pass 5 from house 2 and put it in office 3',
  'ltlequ': '!locality_5 U (house_2&&<>(p_pass_5&&<>(office_3&&pd)))',
  'Spot LTL': '!locality_5 U (house_2 & F(p_pass_5 & F(office_3 & pd)))'},
 {'nlTask': 'Ensure you keep moving box 2 from store 4 to hall 8',
  'ltlequ': '[]<>(store_4&&<>(p_box_2&&<>(hall_8&&pd)))',
  'Spot LTL': 'GF(store_4 & F(p_box_2 & F(hall_8 & pd)))'},
 {'nlTask': 'Refrain from entering park 4 until you arrive at street 3, and then take takeout 2 from store 7 to bench 3',
  'ltlequ': '!park_4 U street_3&&<>(store_7&&<>(p_takeout_2&&<>(bench_3&&pd)))',
  'Spot LTL': '(!park_4 U street_3) & F(store_7 & F(p_takeout_2 & F(bench_3 & pd)))'},
 {'nlTask': 'Ensure that you never pick up box 3',
  'ltlequ': '[]!p_box_3',
  'Spot LTL': 'G!p_box_3'},
 {'nlTask': 'Persistently photograph building 5 while maintaining consistent visits to charger 4',
  'ltlequ': '[]<>(building_5&&photo)&&[]<>charger_4',
  'Spot LTL': 'GF(building_5 & photo) & GFcharger_4'},
 {'nlTask': 'Retrieve letter 3 at post office 1 and take it to house 2',
  'ltlequ': '<>(post_office_1&&<>(p_letter_3&&<>(house_2&&pd)))',
  'Spot LTL': 'F(post_office_1 & F(p_letter_3 & F(house_2 & pd)))'},
 {'nlTask': 'Do not pick up cone 2 until you go to intersection 4',
  'ltlequ': '!p_cone_2 U intersection_4',
  'Spot LTL': '!p_cone_2 U intersection_4'},
 {'nlTask': 'Ensure you never go to street 3 while traveling to building 4',
  'ltlequ': '[]!street_3&&<>building_4',
  'Spot LTL': 'G!street_3 & Fbuilding_4'},
 {'nlTask': 'Keep returning to car 3 as you work your way to building 2',
  'ltlequ': '[]<>car_3&&<>building_2',
  'Spot LTL': 'GFcar_3 & Fbuilding_2'},
 {'nlTask': 'Continuously take a picture of area 51 while also repeatedly visiting charger 4',
  'ltlequ': '[]<>(area_51&&photo)&&[]<>charger_4',
  'Spot LTL': 'GF(area_51 & photo) & GFcharger_4'},
 {'nlTask': 'Take a picture of statue 2, but only after reaching park 5',
  'ltlequ': '<>(park_5&&<>(statue_2&&photo))',
  'Spot LTL': 'F(park_5 & F(photo & statue_2))'},
 {'nlTask': 'Ensure parking lot 8 is not visited while traveling to street 5',
  'ltlequ': '[]!parking_lot_8&&<>street_5',
  'Spot LTL': 'G!parking_lot_8 & Fstreet_5'},
 {'nlTask': 'Do not go to building 9 under any circumstances',
  'ltlequ': '[]!building_9',
  'Spot LTL': 'G!building_9'},
 {'nlTask': 'Do not go to park 3 as you take a picture of monument 3',
  'ltlequ': '[]!park_3&&<>(monument_3&&photo)',
  'Spot LTL': 'F(monument_3 & photo) & G!park_3'},
 {'nlTask': 'Get package 4 from store 2 and subsequently transport it to house 4',
  'ltlequ': '<>(store_2&&<>(p_package_4&&<>(house_4&&pd)))',
  'Spot LTL': 'F(store_2 & F(p_package_4 & F(house_4 & pd)))'},
 {'nlTask': 'Eventually visit section 3 while refraining from entering hall 5 at any time',
  'ltlequ': '<>section_3&&[]!hall_5',
  'Spot LTL': 'Fsection_3 & G!hall_5'},
 {'nlTask': 'Do not enter park 4 until you reach street 3 as you take takeout 2 from store 7 to bench 3',
  'ltlequ': '!park_4 U street_3&&<>(store_7&&<>(p_takeout_2&&<>(bench_3&&pd)))',
  'Spot LTL': '(!park_4 U street_3) & F(store_7 & F(p_takeout_2 & F(bench_3 & pd)))'},
 {'nlTask': 'Ensure you keep capturing photos of area 51 while consistently revisiting charger 4',
  'ltlequ': '[]<>(area_51&&photo)&&[]<>charger_4',
  'Spot LTL': 'GF(area_51 & photo) & GFcharger_4'},
 {'nlTask': 'Ensure you stay in building 2 until you make your way to path 3',
  'ltlequ': 'building_2 U path_3',
  'Spot LTL': 'building_2 U path_3'},
 {'nlTask': 'Do not go to parking lot 4 before arriving at building 8',
  'ltlequ': '!parking_lot_4 U building_8',
  'Spot LTL': '!parking_lot_4 U building_8'},
 {'nlTask': 'Always eventually visit parking lot 4, and ensure that you eventually go to car 5, pick up document 4, and then go to car 6 and deliver it',
  'ltlequ': '[]<>parking_lot_4&&<>(car_5&&<>(p_document_4&&<>(car_6&&pd)))',
  'Spot LTL': 'GFparking_lot_4 & F(car_5 & F(p_document_4 & F(car_6 & pd)))'},
 {'nlTask': 'Continuously transport crate 8 from warehouse 4 to store 8 while repeatedly visiting charger 2',
  'ltlequ': '[]<>(warehouse_4&&<>(p_crate_8&&<>(store_8&&pd)))&&[]<>charger_2',
  'Spot LTL': 'GF(warehouse_4 & F(p_crate_8 & F(pd & store_8))) & GFcharger_2'},
 {'nlTask': 'Go to house 4, collect trash 4, and place it at garbage dump 1',
  'ltlequ': '<>(house_4&&<>(p_trash_4&&<>(garbage_dump_1&&pd)))',
  'Spot LTL': 'F(house_4 & F(p_trash_4 & F(garbage_dump_1 & pd)))'},
 {'nlTask': 'Keep visiting charger 9 as you keep taking crate 2 from warehouse 8 to store 2',
  'ltlequ': '[]<>charger_9&&[]<>(warehouse_8&&<>(p_crate_2&&<>(store_2&&pd)))',
  'Spot LTL': 'GFcharger_9 & GF(warehouse_8 & F(p_crate_2 & F(pd & store_2)))'},
 {'nlTask': 'Pick up pass 2 from house 3 and deliver it to office 2, ensuring you do not enter street 5 before retrieving pass 2',
  'ltlequ': '<>(house_3&&<>(p_pass_2&&<>(office_2&&pd)))&&!street_5 U p_pass_2',
  'Spot LTL': 'F(house_3 & F(p_pass_2 & F(office_2 & pd))) & (!street_5 U p_pass_2)'},
 {'nlTask': 'Go to house 4 to pick up stack 4 and then proceed to street 2 and stay there',
  'ltlequ': '<>(house_4&&<>(p_stack_4&&<>(street_2&&[]street_2)))',
  'Spot LTL': 'F(house_4 & F(p_stack_4 & F(street_2 & Gstreet_2)))'},
 {'nlTask': 'Keep photographing car 1, ensuring you never enter parking lot 9',
  'ltlequ': '[]<>(car_1&&photo)&&[]!parking_lot_9',
  'Spot LTL': 'GF(car_1 & photo) & G!parking_lot_9'},
 {'nlTask': 'Remain at building 2 until you have reached path 3',
  'ltlequ': 'building_2 U path_3',
  'Spot LTL': 'building_2 U path_3'},
 {'nlTask': 'Remain in street 6 until you arrive at intersection 8',
  'ltlequ': 'street_6 U intersection_8',
  'Spot LTL': 'street_6 U intersection_8'},
 {'nlTask': 'Remain in house 4 until you arrive at room 2',
  'ltlequ': 'house_4 U room_2',
  'Spot LTL': 'house_4 U room_2'},
 {'nlTask': 'Keep delivering crate 1 from storage 4 to office 2 over and over',
  'ltlequ': '[]<>(storage_4&&<>(p_crate_1&&<>(office_2&&pd)))',
  'Spot LTL': 'GF(storage_4 & F(p_crate_1 & F(office_2 & pd)))'},
 {'nlTask': 'Avoid going to park 5 until you reach intersection 5 as you take a photo of monument 3',
  'ltlequ': '!park_5 U intersection_5&&<>(monument_3&&photo)',
  'Spot LTL': '(!park_5 U intersection_5) & F(monument_3 & photo)'},
 {'nlTask': 'Remain in locality 6 until you take package 3 from store 8 and deliver it to house 5',
  'ltlequ': 'locality_6 U (store_8&&<>(p_package_3&&<>(house_5&&pd)))',
  'Spot LTL': 'locality_6 U (store_8 & F(p_package_3 & F(house_5 & pd)))'},
 {'nlTask': 'Deliver letter 3 to house 2 from post office 1',
  'ltlequ': '<>(post_office_1&&<>(p_letter_3&&<>(house_2&&pd)))',
  'Spot LTL': 'F(post_office_1 & F(p_letter_3 & F(house_2 & pd)))'},
 {'nlTask': 'Avoid street 4 as you transport package 8 from store 7 to house 2',
  'ltlequ': '[]!street_4&&<>(store_7&&<>(p_package_8&&<>(house_2&&pd)))',
  'Spot LTL': 'G!street_4 & F(store_7 & F(p_package_8 & F(house_2 & pd)))'},
 {'nlTask': 'Do not enter street 4 before reaching intersection 6 and then stay in street 4 continuously',
  'ltlequ': '!street_4 U intersection_6&&<>[]street_4',
  'Spot LTL': '(!street_4 U intersection_6) & FGstreet_4'},
 {'nlTask': 'Retrieve brochure 2 from table 8 and then take it to table 1',
  'ltlequ': '<>(table_8&&<>(p_brochure_2&&<>(table_1&&pd)))',
  'Spot LTL': 'F(table_8 & F(p_brochure_2 & F(pd & table_1)))'},
 {'nlTask': 'Go to street 5 and then go to building 2 and stay there',
  'ltlequ': '<>(street_5&&<>(building_2&&[]building_2))',
  'Spot LTL': 'F(street_5 & F(building_2 & Gbuilding_2))'},
 {'nlTask': 'Stay in street 4 until you take a photo of house 1',
  'ltlequ': 'street_4 U (house_1&&photo)',
  'Spot LTL': 'street_4 U (house_1 & photo)'},
 {'nlTask': 'Eventually(Ensure you capture a photo of monument 12 and stay there)',
  'ltlequ': '<>(monument_12&&photo&&[]monument_12)',
  'Spot LTL': 'F(monument_12 & photo & Gmonument_12)'},
 {'nlTask': 'Remain in street 6 before getting to intersection 8',
  'ltlequ': 'street_6 U intersection_8',
  'Spot LTL': 'street_6 U intersection_8'},
 {'nlTask': 'Stay away from intersection 1 until you get to street 6, and afterward, deliver cone 3 from street 2 to intersection 1',
  'ltlequ': '!intersection_1 U street_6&&<>(street_2&&<>(p_cone_3&&<>(intersection_1&&pd)))',
  'Spot LTL': '(!intersection_1 U street_6) & F(street_2 & F(p_cone_3 & F(intersection_1 & pd)))'},
 {'nlTask': 'Keep visiting street 5',
  'ltlequ': '[]<>street_5',
  'Spot LTL': 'GFstreet_5'},
 {'nlTask': 'Stay in county 4 and keep taking package 4 from office 3 to office 8',
  'ltlequ': '[]county_4&&[]<>(office_3&&<>(p_package_4&&<>(office_8&&pd)))',
  'Spot LTL': 'Gcounty_4 & GF(office_3 & F(p_package_4 & F(office_8 & pd)))'},
 {'nlTask': 'Remain in parking lot 9 until you take a picture of car 2',
  'ltlequ': 'parking_lot_9 U (car_2&&photo)',
  'Spot LTL': 'parking_lot_9 U (car_2 & photo)'},
 {'nlTask': 'Eventually (take a picture of landmark 9 and stay at landmark 9 permanently)',
  'ltlequ': '<>(landmark_9&&photo&&[]landmark_9)',
  'Spot LTL': 'F(landmark_9 & photo & Glandmark_9)'},
 {'nlTask': 'Put down whatever you are carrying and head to parking lot 2',
  'ltlequ': '<>(pd&&<>parking_lot_2)',
  'Spot LTL': 'F(pd & Fparking_lot_2)'},
 {'nlTask': 'Refrain from entering store 4 until you arrive at street 6, while delivering package 8 from office 2 to store 4',
  'ltlequ': '!store_4 U street_6&&<>(office_2&&<>(p_package_8&&<>(store_4&&pd)))',
  'Spot LTL': '(!store_4 U street_6) & F(office_2 & F(p_package_8 & F(pd & store_4)))'},
 {'nlTask': 'Capture a photo of arch 4 but never go to park 2',
  'ltlequ': '<>(arch_4&&photo)&&[]!park_2',
  'Spot LTL': 'F(arch_4 & photo) & G!park_2'},
 {'nlTask': 'Stay in street 6 until you reach intersection 8',
  'ltlequ': 'street_6 U intersection_8',
  'Spot LTL': 'street_6 U intersection_8'},
 {'nlTask': 'Take tin can 4 from table 4, deposit it in trash can 5, and ensure you do not enter hallway 2',
  'ltlequ': '<>(table_4&&<>(p_tin_can_4&&<>(trash_can_5&&pd)))&&[]!hallway_2',
  'Spot LTL': 'F(table_4 & F(p_tin_can_4 & F(pd & trash_can_5))) & G!hallway_2'},
 {'nlTask': 'Capture the image of monument 1 but refrain from entering monument until you have reached park 4',
  'ltlequ': '<>(monument_1&&photo)&&!monument_1 U park_4',
  'Spot LTL': 'F(monument_1 & photo) & (!monument_1 U park_4)'},
 {'nlTask': 'Do not go to store 4 until you reach street 6, while ensuring you transport package 8 from office 2 to store 4',
  'ltlequ': '!store_4 U street_6&&<>(office_2&&<>(p_package_8&&<>(store_4&&pd)))',
  'Spot LTL': '(!store_4 U street_6) & F(office_2 & F(p_package_8 & F(pd & store_4)))'},
 {'nlTask': 'Stay within park 2 until you capture a photo of monument 13',
  'ltlequ': 'park_2 U (monument_13&&photo)',
  'Spot LTL': 'park_2 U (monument_13 & photo)'},
 {'nlTask': 'Take letter 4 from office 5 to house 2',
  'ltlequ': '<>(office_5&&<>(p_letter_4&&<>(house_2&&pd)))',
  'Spot LTL': 'F(office_5 & F(p_letter_4 & F(house_2 & pd)))'},
 {'nlTask': 'Remain in area 5 until you take package 8 from store 2 and deliver it to house 9',
  'ltlequ': 'area_5 U (store_2&&<>(p_package_8&&<>(house_9&&pd)))',
  'Spot LTL': 'area_5 U (store_2 & F(p_package_8 & F(house_9 & pd)))'},
 {'nlTask': 'Keep taking a picture of monument 8 but do not go to monument 8 until you reach park 4',
  'ltlequ': '[]<>(monument_8&&photo)&&!monument_8 U park_4',
  'Spot LTL': 'GF(monument_8 & photo) & (!monument_8 U park_4)'},
 {'nlTask': 'Always remain in locality 7 while transporting letter 1 from office 4 to house 1',
  'ltlequ': '[]locality_7&&<>(office_4&&<>(p_letter_1&&<>(house_1&&pd)))',
  'Spot LTL': 'Glocality_7 & F(office_4 & F(p_letter_1 & F(house_1 & pd)))'},

In [295]:
df = pd.json_normalize(d).rename(columns={'ltlequ': 'original LTL', 'nlTask': 'original NL'})
df['APs'] = df['Spot LTL'].apply(lambda x: extract_atomic_propositions(x))
df['ap_NL'] = df.apply(
    lambda row: swap_row_propositions(row, 'APs', 'original NL'), 
    axis=1
)
df['dict_AP']=df['APs'].apply(lambda x: {x.removeprefix('p_').replace('_', ' ') : x for x in x})

def dynamic_replace(row):
    text = row['ap_NL']
    mapping = row['dict_AP']
    
    # Split the string, replace words found in the dict, join back
    # Using mapping.get(word, word) returns the replacement OR the original word
    return " ".join([mapping.get(word, word) for word in text.split()])
df['ap_NL'] = df.apply(dynamic_replace, axis=1)
df.to_csv('./processed_data/ConformalNL2LTL/processed_data.csv', index=False, sep=';')
df

,original NL,original LTL,Spot LTL,APs,ap_NL,dict_AP
0,Do not enter garage 1 until you take a picture...,!garage_1 U (landmark_5&&photo),!garage_1 U (landmark_5 & photo),"[garage_1, landmark_5, photo]",Do not enter garage_1 until you take a picture...,"{'garage 1': 'garage_1', 'landmark 5': 'landma..."
1,Ensure you never retrieve package 5,[]!p_package_5,G!p_package_5,[p_package_5],Ensure you never retrieve package 5,{'package 5': 'p_package_5'}
2,Do not go to street 7 while you take package 3...,[]!street_7&&<>(store_9&&<>(p_package_3&&<>(ho...,G!street_7 & F(store_9 & F(p_package_3 & F(hou...,"[house_1, pd, p_package_3, street_7, store_9]",Do not go to street_7 while you take package 3...,"{'house 1': 'house_1', 'pd': 'pd', 'package 3'..."
3,"Start by visiting mall 5 to pick up box 4, and...",<>(mall_5&&<>(p_box_4&&<>(house_1&&pd))),F(mall_5 & F(p_box_4 & F(house_1 & pd))),"[mall_5, p_box_4, house_1, pd]","Start by visiting mall_5 to pick up box 4, and...","{'mall 5': 'mall_5', 'box 4': 'p_box_4', 'hous..."
4,Do not go to intersection 1 before arriving at...,!intersection_1 U street_6&&<>(street_2&&<>(p_...,(!intersection_1 U street_6) & F(street_2 & F(...,"[pd, intersection_1, street_6, street_2, p_con...",Do not go to intersection_1 before arriving at...,"{'pd': 'pd', 'intersection 1': 'intersection_1..."
...,...,...,...,...,...,...
673,Go to office 3 to pick up document 1 and move ...,<>(office_3&&<>(p_document_1&&<>(street_2&&[]s...,F(office_3 & F(p_document_1 & F(street_2 & Gst...,"[street_2, office_3, p_document_1]",Go to office_3 to pick up document 1 and move ...,"{'street 2': 'street_2', 'office 3': 'office_3..."
674,Stay in locality 3 until you reach office 4,locality_3 U office_4,locality_3 U office_4,"[office_4, locality_3]",Stay in locality_3 until you reach office_4,"{'office 4': 'office_4', 'locality 3': 'locali..."
675,Go to park 8 and never leave,<>[]park_8,FGpark_8,[park_8],Go to park_8 and never leave,{'park 8': 'park_8'}
676,Avoid entering intersection 5 until you reach ...,!intersection_5 U street_4&&<>(house_4&&<>(p_p...,(!intersection_5 U street_4) & F(house_4 & F(p...,"[pd, intersection_5, street_4, house_4, p_pass...",Avoid entering intersection_5 until you reach ...,"{'pd': 'pd', 'intersection 5': 'intersection_5..."
677,Refrain from going to room 2 until you pick up...,!room_2 U (kitchen_1&&<>(p_bottle_4&&<>(table_...,!room_2 U (kitchen_1 & F(p_bottle_4 & F(pd & t...,"[pd, room_2, kitchen_1, p_bottle_4, table_4]",Refrain from going to room_2 until you pick up...,"{'pd': 'pd', 'room 2': 'room_2', 'kitchen 1': ..."

In [290]:
df

,original NL,original LTL,Spot LTL,APs,ap_NL
0,Do not enter garage 1 until you take a picture...,!garage_1 U (landmark_5&&photo),!garage_1 U (landmark_5 & photo),"[garage_1, landmark_5, photo]",Do not enter garage_1 until you take a picture...
1,Ensure you never retrieve package 5,[]!p_package_5,G!p_package_5,[p_package_5],Ensure you never retrieve package 5
2,Do not go to street 7 while you take package 3...,[]!street_7&&<>(store_9&&<>(p_package_3&&<>(ho...,G!street_7 & F(store_9 & F(p_package_3 & F(hou...,"[house_1, pd, p_package_3, street_7, store_9]",Do not go to street_7 while you take package 3...
3,"Start by visiting mall 5 to pick up box 4, and...",<>(mall_5&&<>(p_box_4&&<>(house_1&&pd))),F(mall_5 & F(p_box_4 & F(house_1 & pd))),"[mall_5, p_box_4, house_1, pd]","Start by visiting mall_5 to pick up box 4, and..."
4,Do not go to intersection 1 before arriving at...,!intersection_1 U street_6&&<>(street_2&&<>(p_...,(!intersection_1 U street_6) & F(street_2 & F(...,"[pd, intersection_1, street_6, street_2, p_con...",Do not go to intersection_1 before arriving at...
...,...,...,...,...,...
673,Go to office 3 to pick up document 1 and move ...,<>(office_3&&<>(p_document_1&&<>(street_2&&[]s...,F(office_3 & F(p_document_1 & F(street_2 & Gst...,"[street_2, office_3, p_document_1]",Go to office_3 to pick up document 1 and move ...
674,Stay in locality 3 until you reach office 4,locality_3 U office_4,locality_3 U office_4,"[office_4, locality_3]",Stay in locality_3 until you reach office_4
675,Go to park 8 and never leave,<>[]park_8,FGpark_8,[park_8],Go to park_8 and never leave
676,Avoid entering intersection 5 until you reach ...,!intersection_5 U street_4&&<>(house_4&&<>(p_p...,(!intersection_5 U street_4) & F(house_4 & F(p...,"[pd, intersection_5, street_4, house_4, p_pass...",Avoid entering intersection_5 until you reach ...
677,Refrain from going to room 2 until you pick up...,!room_2 U (kitchen_1&&<>(p_bottle_4&&<>(table_...,!room_2 U (kitchen_1 & F(p_bottle_4 & F(pd & t...,"[pd, room_2, kitchen_1, p_bottle_4, table_4]",Refrain from going to room_2 until you pick up...

In [291]:
d[0]['ltlequ'][0][:-1]

''

In [183]:
str(simplify_formula('<>(mall_5&&<>(p_box_4&&<>(house_1&&pd)))'))

'F(mall_5 & F(p_box_4 & F(house_1 & pd)))'

In [187]:
str(simplify_formula('!garage_1 U (landmark_5&&photo)'))

'!garage_1 U (landmark_5 & photo)'